### ISSUE TITLE
Fjerne lagvelger ved visning av data for kun en kilde

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#101]
Hvis en generert demonstrator (eller andre?) er satt opp med kun en kilde - ikke vis lag/kildevelger oppe til høyre

**Comment by atlefren** [comment]
Betyr dette at vi også dropper lasteindikasjon etc?

**Comment by havardgj** [comment]
Ja. Jeg tror det er ryddigere - selv om det i noen tilfeller naturligvis kan være nyttig å se at noe lastes. Alternativet hadde vært å behold ved lasting og evt. feil, men skjult når alt er lastet, men jeg antar at logikken blir en del enklere hvis den kun må forhold seg til antalle kilder og det er et helt OK kompromiss.

________________________________

**Comment by atlefren** [comment]
Den er god!

Fikset, pull request inne, venter på tilbakemelding

Demo på kun et kartlag: http://knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=difo&komm=1601&layer=norges_grunnkart_graatone&geomFilter=true&showGeom=true

**Comment by havardgj** [comment]
Ser bra ut!

________________________________
