### ISSUE TITLE
Bruke kysten som linje

### ISSUE THREAD

**Issue by atlefren** [knreise/demonstratorer#128]
1. Lag generalisert linjegeometri av kystlinje
2. Støtte for GeoJSON i KNreiseAPI
3. Lagre linje på webserver

**Comment by atlefren** [comment]
Steg for å generere forenklet kystlinje:

1. Last ned N500 Kartdata, UTM33, hele landet, FGDB fra data.kartverket.no
2. Åpne med Qgis 2.10 (har støtte for FGDB)
3. Åpne filgeodatabase 
4. Velg laget Arealdekke
5. Kjør "polygons to lines" (fra processing toolbar)
6. Plukk ut kystlinja
7. Edit layer, klipp vekk svenskegrensa
8. kopier kystlinje til nytt layer
9. Lagre som GeoJSON
10. Manuelt endre fra MultiLineString til LineString
11. lag turf.js-script som kjører simplify, (var simplified = turf.simplify(line.features[0], 0.01, true);)
12. Lagre geojson-fil på webserver

**Comment by havardgj** [comment]
Dette fungerer veldig fint, men ser at begrepet kyst i denne sammenhengen ikke var presist nok definert. Denne linja er nok en helt riktig kystlinje og forenklingen fungerer fint. Problemer er at vi ikke får med øyene langskysten. Og for å kunne bruke den som basis for å hente ut innhold langs "kysten", så er det nok litt problematisk at vi mister hele Lofoten, Senja osv. Er det enkelt å få med også disse?

**Comment by atlefren** [comment]
Jeg tenker at det ikke er så vanskelig å operere med mer enn en linje: en for selve kystlinja (som i dag), pluss linjer for de øyene vi er interesserte i å ha med. Da kan vi kjøre buffer som i dag, og vi slipper at vi får med alt «innenfor» ei stor øy, men kun får det som er langs kystlinja på denne øya også.

**Comment by atlefren** [comment]
Et forsøk her: denne er litt for stor, så det blir endel krøll med nettleseren http://knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=&allstatic=true&buffer=2&linecolor=%230033ff&line=http%3A%2F%2Fknreise.no%2Fdata%2Fkystlinje_oyer.geojson&layer=norges_grunnkart_graatone#7/67.8196/15.3809

**Comment by atlefren** [comment]
En mer forenklet utgave, ser ut til å fungere greit http://knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=&allstatic=true&buffer=2&linecolor=%230033ff&line=http%3A%2F%2Fknreise.no%2Fdata%2Fkystlinje_oyer5.geojson&layer=norges_grunnkart_graatone#7/59.7702/11.272

**Comment by atlefren** [comment]
Kode for dette på https://github.com/knreise/kystlinje_simplify

**Comment by havardgj** [comment]
Ser bra ut.
