### ISSUE TITLE
Vise foto for brukerregistrerte kulturminner

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#129]
Hente ut bilder for brukerregistrerte kulturminner fra Riksantikvarens Husmann-API. Hvis mulig for alle kulturminner slik at bildene også kan vises som thumbnails. Men siden dette må hentes fra eget API, så må en kanskje begrense det til å hente og vise for enkeltobjekt - i detaljvisning. 

- Hents fra tables i stedet for et Layer
- Det skal være mulig å hente bildedata for KulturminnesokID
- http://husmann.ra.no/arcgis/rest/services/Husmann/Husmann/MapServer
- http://husmann.ra.no/arcgis/rest/services/Husmann/Husmann/MapServer/6
- UrlTilBilde

Hente og vise noe metadata for bilde:
- Tittel
- RegistrertAv
- OpphavspersonFotograf: Ole Thor Ripegutu
- Copyright

**Comment by atlefren** [comment]
Det er ikke alle features som ser ut til å ha treff, men ellers ser dette ut til å fungere godt.

Med ett ekstra kall får jeg lasta bilder for alle features, så vi får thumbnails etc:

Litt usikker på styling av bilde-metadata, har gjort et forsøk, men tar gjerne imot innspill

![image](https://cloud.githubusercontent.com/assets/1829927/10480955/d2348cbe-726d-11e5-86f0-7cd7aaf2dbd1.png)

**Comment by atlefren** [comment]
Kan testes på knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=brukerminner&bbox=7.108154296875%2C60.7000723265162%2C11.9091796875%2C62.27303454787818

**Comment by havardgj** [comment]
Dette ser veldig bra ut - jeg kan se på formateringen.


Den 14. okt. 2015 kl. 12.32 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


Kan testes på knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=brukerminner&bbox=7.108154296875%2C60.7000723265162%2C11.9091796875%2C62.27303454787818<http://knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=brukerminner&bbox=7.108154296875%2C60.7000723265162%2C11.9091796875%2C62.27303454787818>

**Comment by havardgj** [comment]
Tenkte jeg skulle se på malen for visning av metadata til foto. Men når jeg nå tester f.eks. Flyktningeruta lokalt (http://localhost:8080/demonstratorer/flyktningeruta.html#11/59.824/11.3659) så feiler hentingen fra Husmann-APIet konsekvent. Mener jeg skal ha hentet alle oppdateringer fra GitHub. Samme kart her http://knreise.github.io/demonstratorer/demonstratorer/flyktningeruta.html viser innholdet som det skal. Hvordan ser dette ut hos deg?

**Comment by atlefren** [comment]
Det var rart. Det fungerer fint hos meg, så veldig rart det ikke fungerer hos deg. Cache?

**Comment by havardgj** [comment]
Fungerer fint her nå. Kan ha vært cache-problemer, ja. Har ellers lagt til og pushet noen visuelle justeringer.
