### ISSUE TITLE
Konfigurasjonsvalg for å starte med brukerens posisjon

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#130]
Mulighet for å sette opp konfigurasjon til å begynne med å spørre etter posisjon og vente med å hente kart og data til posisjon er hentet
Ellers samme logikk som i dag er tilgjengelig ved klikk på knapp for posisjonering - med feilmelding om man er utenfor kart etc.

**Comment by atlefren** [comment]
Da skal denne være på plass, har gjort et par forutsetninger:

1. Hvis parameteret initUserPos er satt til true spør nettleseren om brukerens posisjon
2. Hvis alt går fint startes kartet med brukerens posisjon, og "følg brukeren" er PÅ
3. Hvis posisjonering feiler ser den om det finnes en posisjon i url-hash, og bruker i så fall denne
4. hvis 3 feiler bruker den default-bounds for demonstratoren

demo: http://knreise.github.io/demonstratorer/demonstratorer/norge.html

**Comment by havardgj** [comment]
Forutsetningene ser rimelige ut og så vidt jeg kan se fungerer dette akkurat som det skal.
