### ISSUE TITLE
Visning av multipolygoner for kulturminne-lokasjoner

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#131]
Ved visning av polygon for lokasjon - vise alle polygoner som er knyttet til den aktuelle lokasjon.

Eksempel på spørring som returnerer flere polygoner:

    SELECT ?lok where
    {
         <https://data.kulturminne.no/askeladden/lokalitet/173268> ?p ?lok .
     }

https://sparql.kulturminne.no/?default-graph-uri=&query=SELECT+%3Flok+where%0D%0A%7B%0D%0A++%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Flokalitet%2F173268%3E+%3Fp+%3Flok+.%0D%0A%7D&format=application%2Fsparql-results%2Bjson&timeout=0&debug=on

Update:
Foreslår at problemet med krash får vente og at du prioriterer dette med visningen i denne omgangen - en eller begge strategier for å hindre at polygoner for Oscarsborg forsvinner mens man egentlig ser på området for akkurat disse polygonene.

2 forslag til ting som kan prøves for å utbedre (uten at jeg har tenkt så mye over omfang og "feasibility"):

- Alltid vise polygon for valgt punkt (dvs klikker du på et punkt vises alltid geometri, uavhengig av hvor mye som måtte være i kartet)
- Ikke skjule polygon når punktet forsvinner fra kartet, men når selve polygonet forsvinner fra kart

**Comment by atlefren** [comment]
Skal nå være løst, demo: http://knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=riksantikvaren&bbox=10.579533576965332%2C59.67138142024958%2C10.598287582397461%2C59.677881934258316&layer=norges_grunnkart_graatone#16/59.6771/10.594



ellers: spørringen kan skrives om til:

    SELECT ?lok where {
        <https://data.kulturminne.no/askeladden/lokalitet/173268> <https://data.kulturminne.no/askeladden/schema/geo/area/etrs89> ?lok . 
    }

for å kun få tilbake polygoner

**Comment by havardgj** [comment]
Ser veldig bra ut når det vises. Men ser at visningen ikke er helt stabil. Etter lasting er det noen ganger at polygonene for Oscarsborg bare vises et kort sekund for så å bli borte. Eneste måte å få vist dem på er da å laste siden på nytt - panorering og zooming inn og ut fungerer ikke. Andre ganger vises polygonene til en begynner å panorere eller zoome.

**Comment by atlefren** [comment]
Skal sjekke opp, derfor du tester ;)

**Comment by atlefren** [comment]
Slik ser det ut hos meg, er det slik hos deg, eller værre?
![screen2](https://cloud.githubusercontent.com/assets/1829927/10458389/ddd0f862-71ca-11e5-9efc-1a336fc4ed30.gif)

**Comment by havardgj** [comment]
Kanskje litt verre? Her med Chrome

https://www.dropbox.com/s/slz5g5wg1314ea0/Screen%20Recorded2015-10-13%2016_57_56.mov?dl=0

**Comment by atlefren** [comment]
Ja, værre, men det har en helt naturlig forklaring.

Selve punktet for oscarsborg (det som har alle geometriene) er punktet jeg starter med omtrent i senter av kartbildet (helt vest på "Bergholmen").

Logikken for polygoner er også slik at den kun viser polygoner for punkter når det er 5 eller mindre punkter synlige i kartet.

Dermed: jeg tror jeg har mitt på det rene når jeg påstår at det "fungerer som forventet", men jeg er helt enig i at det ikke oppfører seg særlig bra, så vi burde kanskje tenke litt mer?

I tillegg er det kanskje litt rart at det er det punktet som er oscarsborg?

**Comment by havardgj** [comment]
Tror jeg forstår. Jeg kan teste litt mer, men opplever vel at jeg ikke klarer å få opp polygonene etter at de forsvinner - selv om jeg zoomer inn og ut og panorerer i kartet.

Samtidig er nok Oscarsborg spesielt krevende. Punktet som velges er nok ikke helt optimalt, men kan ikke se at det er rom for å utvide logikken her - eller hva den evt. skal være.

Vil det være en mulighet å utvide antallet som vises fra 5 til 10?

Den 14. okt. 2015 kl. 10.00 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


Ja, værre, men det har en helt naturlig forklaring.

Selve punktet for oscarsborg (det som har alle geometriene) er punktet jeg starter med omtrent i senter av kartbildet (helt vest på "Bergholmen").

Logikken for polygoner er også slik at den kun viser polygoner for punkter når det er 5 eller mindre punkter synlige i kartet.

Dermed: jeg tror jeg har mitt på det rene når jeg påstår at det "fungerer som forventet", men jeg er helt enig i at det ikke oppfører seg særlig bra, så vi burde kanskje tenke litt mer?

I tillegg er det kanskje litt rart at det er det punktet som er oscarsborg?

**Comment by atlefren** [comment]
Har nå økt til 10

2 forslag til ting som kan prøves for å utbedre (uten at jeg har tenkt så mye over omfang og "feasibility"):

1. Alltid vise polygon for valgt punkt (dvs klikker du på et punkt vises alltid geometri, uavhengig av hvor mye som måtte være i kartet)
2. Ikke skjule polygon når _punktet_ forsvinner fra kartet, men når selve polygonet forsvinner fra kartet

Eller kanskje en kombinasjon av begge?`

Foreslår at du tester igjen og så ser vi hva vi gjør?

**Comment by havardgj** [comment]
Har kun fått testet på mobil så langt, men der krasjer denne visningen nå konsekvent - basert på URLen jeg fikk i går og uten at jeg interagerer med kartet

[image1.PNG]

Den 14. okt. 2015 kl. 12.43 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


Har nå økt til 10

2 forslag til ting som kan prøves for å utbedre (uten at jeg har tenkt så mye over omfang og "feasibility"):

  1.  Alltid vise polygon for valgt punkt (dvs klikker du på et punkt vises alltid geometri, uavhengig av hvor mye som måtte være i kartet)
  2.  Ikke skjule polygon når punktet forsvinner fra kartet, men når selve polygonet forsvinner fra kartet

Eller kanskje en kombinasjon av begge?`

Foreslår at du tester igjen og så ser vi hva vi gjør?

**Comment by atlefren** [comment]
Hmm, ser ikke bildet ditt?

Ser bra ut på min telefon, uten at det hjelper deg noe særlig.

![image](https://cloud.githubusercontent.com/assets/1829927/10482502/da1c2ec2-7278-11e5-94e6-337c5947aad8.png)


Skal ta en runde og sjekke opp denne mer

**Comment by atlefren** [comment]
Hmm

nå har jeg testet på følgende:

- chrome, ie og firefox på windows
- safari på ipad
- chrome på android tlf

og jeg får ikke noe kræsj som det du sendte

kan du teste denne på bastøy:

http://knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=riksantikvaren&bbox=10.579533576965332%2C59.67138142024958%2C10.598287582397461%2C59.677881934258316&layer=norges_grunnkart_graatone#16/59.3818/10.5329

**Comment by havardgj** [comment]
Denne fungerer helt fint både i Safari og Chrome med iOS. Kan teste den andre med Oscarsborg litt mer.


14. okt. 2015 kl. 16.05 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


Hmm

nå har jeg testet på følgende:

  *   chrome, ie og firefox på windows
  *   safari på ipad
  *   chrome på android tlf

og jeg får ikke noe kræsj som det du sendte

kan du teste denne på bastøy:

http://knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=riksantikvaren&bbox=10.579533576965332%2C59.67138142024958%2C10.598287582397461%2C59.677881934258316&layer=norges_grunnkart_graatone#16/59.3818/10.5329

**Comment by havardgj** [comment]
Har testet rundt Oscarsborg med iOS (iPhone 6). Både Safari og Chrome krasjer ganske konsekvent. Ser ut til at det er i forbindelse med behandling/rendring av polygonene for Oscarsborg. Hvis en ikke rører kartet ved opptegning så går det av og til bra å få polygonene tegnet opp, men så fort man da begynner å bevege kartet, så krasjer det. Og noen ganger krasjer det før de er tegnet opp.

Kanskje dette rett og slett er et eksempel på data som er for komplekse til å vises på denne måten i en mobil nettleser...? Evt. begrenset til iOS? En kunne kanskje i teorien forenklet polygonene on-the-fly, men vet ikke om det ville ha hjulpet?

Når det gjelder visning ellers så ser jeg at dette er krevende med det punktet vi har og de polygonene som er knyttet til for akkurat Oscarsborg. Visning ved klikk og å ikke fjerne selv om punkt går utenfor høres begge ut som fornuftige valg for å unngå den oppførselen som nå er logisk, men i praksis oppleves som litt rar.

Skal se og tenke litt mer på det.


14. okt. 2015 kl. 16.21 skrev Håvard Johansen <Havard.Johansen@kulturradet.no<mailto:Havard.Johansen@kulturradet.no>>:

Denne fungerer helt fint både i Safari og Chrome med iOS. Kan teste den andre med Oscarsborg litt mer.


14. okt. 2015 kl. 16.05 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


Hmm

nå har jeg testet på følgende:

  *   chrome, ie og firefox på windows
  *   safari på ipad
  *   chrome på android tlf

og jeg får ikke noe kræsj som det du sendte

kan du teste denne på bastøy:

http://knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=riksantikvaren&bbox=10.579533576965332%2C59.67138142024958%2C10.598287582397461%2C59.677881934258316&layer=norges_grunnkart_graatone#16/59.3818/10.5329

**Comment by havardgj** [comment]
Har nå testet litt mer i forhold til krasj. Har testet i emulator for å se om jeg kunne få ut mer informasjon, men der krasjer det ikke...

Foreslår at probelement med krash får vente og at du prioriterer dette med visningen i denne omgangen - en eller begge strategier for å hindre at polygoner for Oscarsborg mens man egentlig ser på området for akkurat disse polygonene. 

Kan det evt. være en ide å ikke fjerne polygoner fra visningen i det hele tatt - hvis de først er vist så la dem stå? Eller vil det være risikabelt eller ulogisk i forhold til andre ting?

**Comment by atlefren** [comment]
Testet nå å ikke fjerne polygoner fra visningen i det hele tatt. Det ble litt logikk for å ikke legge til samme polygon flere ganger, og har også lagt til funksjonalitet for å fjerne dem hvis man zoomer for langt ut. Det ser ut til å fungere fint der jeg tester, men krever gjerne litt mer testing. Tilgjengelig på github.io

**Comment by havardgj** [comment]
Testet med desktop Chrome og Safari og Safari på iOS - ser ut til å fungere fint. Ingen krasj og dynamikk for visning som forventet. Det er noen få scenarier som ikke er helt optimale ennå (typisk rundt Oscarsborg), men også her fungerer det mye bedre enn tidligere og jeg tror dette er mer enn bra nok i denne omgang.
