### ISSUE TITLE
Flere medieobjekt i detaljvisning

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#133]
Hente og vise flere medieobjekt i detaljvisning. I første omgang aktuelt for datasett som hentes via Norvegiana. 

Vise første objekt som i dag, men legge til knapper for navigasjon til neste objekt - og tilbake

![intern_nav2](https://cloud.githubusercontent.com/assets/8926528/10282747/a8cae49c-6b7c-11e5-83d9-64b9708f795c.png)

**Comment by atlefren** [comment]
Har du noen eksempler på innhold som har mer enn et bilde? 

Eksempelet du bruker har bare ett (http://kulturnett2.delving.org/api/search?id=kulturnett_difo_H-DF%2FDF.7099&format=json)

Er dette det samme problemet vi fant i #134 ?

**Comment by havardgj** [comment]
Denne har en video og ett bilder:
http://kulturnett2.delving.org/api/search?id=kulturnett_difo_H-DF%2FDF.4917&format=json

Denne har tre bilder:
http://kulturnett2.delving.org/api/search?id=kulturnett_difo_H-DF%2FDF.1885&format=json

Fungerer det?

**Comment by atlefren** [comment]
supert! Ser lovende ut!

**Comment by atlefren** [comment]
Har nå på plass liste for flere bilder, håndterer enda ikke video/lyd/bilde på samme objekt, men håper dette er i rette bane @havardgj ?

![medialist](https://cloud.githubusercontent.com/assets/1829927/10814964/5ad9c6a8-7e29-11e5-9ef7-308c8aa0b0fe.gif)

**Comment by havardgj** [comment]
Absolutt - dette ser veldig bra ut.

29. okt. 2015 kl. 10.40 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


Har nå på plass liste for flere bilder, håndterer enda ikke video/lyd/bilde på samme objekt, men håper dette er i rette bane @havardgj<https://github.com/havardgj> ?

[medialist]<https://cloud.githubusercontent.com/assets/1829927/10814964/5ad9c6a8-7e29-11e5-9ef7-308c8aa0b0fe.gif>

**Comment by atlefren** [comment]
Da har jeg fått på plass støtte for lyd og video også

http://knreise.github.io/demonstratorer/demonstratorer/kjaerlighetsstien.html#18/59.3878/9.1765:norvegiana_kulturnett_difo_H-DF%252FDF.4919

og http://knreise.github.io/demonstratorer/demonstratorer/kjaerlighetsstien.html#18/59.3865/9.1728 

er gode startpunkter for å teste

**Comment by havardgj** [comment]
Ser veldig bra ut!

Den eneste justeringen jeg tenker på er muligheten for å disable forrige når man er på første og neste når man er på siste bilde/video - disable knappen slik at den ikke er klikkbar og gjør den lysere (alpha?). En løsning der en går i sirkel som nå er helt akseptabelt og i noen tilfeller kan det være greit  f.eks. kunne komme fra siste til første, men i de fleste tilfeller tror jeg det er bedre om en kan få en indikasjon på første/siste.


29. okt. 2015 kl. 13.15 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


Da har jeg fått på plass støtte for lyd og video også

http://knreise.github.io/demonstratorer/demonstratorer/kjaerlighetsstien.html#18/59.3878/9.1765:norvegiana_kulturnett_difo_H-DF%252FDF.4919

og http://knreise.github.io/demonstratorer/demonstratorer/kjaerlighetsstien.html#18/59.3865/9.1728

er gode startpunkter for å teste

**Comment by atlefren** [comment]
Ja, tenkte litt på det, men gjorde det ikke, skal se på det!
