### ISSUE TITLE
Prioritere video ved tilgang på flere medieobjekt

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#134]
I påvente av mulighet for visning av flere medieobjekt - prioritere video før foto. I første omgang aktuelt for Digitalt fortalt.

Kan utgå om en ser at visning av flere objekt kommer på plass (#133)

**Comment by atlefren** [comment]
@havardgj har du noen eksempler på objekter fra digitalt fortalt som har både bilde og video? Klarer ikke å finne noen nå

**Comment by havardgj** [comment]
http://digitaltfortalt.no/things/kunstnarmilj-p-gvarv/H-DF/DF.1885

http://localhost:8080/demonstratorer/kjaerlighetsstien.html#21/59.3864/9.1729:norvegiana_kulturnett_difo_H-DF%252FDF.1885

**Comment by atlefren** [comment]
hmm

Her er responsen jeg får fra norwegiana om dette objektet: https://gist.github.com/atlefren/80868eddffdd548dc10f

Jeg ser at det er 3 bilder i abm_imageUri (og ett i delving_thumbnail, som er det vi bruker), men jeg finner ikke noe video? Kan det være noe feil med oppsett i norvegiana?

**Comment by havardgj** [comment]
Beklager at jeg ikke sjekket dette. Denne har video i tillegg til de tre bildene i Digitalt fortalt, men av en eller annen grunn blir den ikke returnert i APIet. 

Denne har en video og ett bilde:

http://digitaltfortalt.no/things/det-gamle-apoteket-p-gvarv/H-DF/DF.4917

Og så vidt jeg kan se har den riktig verdi  for video:

<abm:videoUri>
http://mm.dimu.no/multimedia/012ToAGP.mp4?mmid=012ToAGP
</abm:videoUri>

Men her ser jeg at video faktisk blir vist i demonstratorene - er det tilfeldig eller er faktisk video prioritert nå? Sånn at når video ikke dukker opp så er det en feil i Norvegiana i stedet?

**Comment by atlefren** [comment]
Skjønner at det er mye å sjekke!

Sjekka opp http://digitaltfortalt.no/things/det-gamle-apoteket-p-gvarv/H-DF/DF.4917 nå

Det har europeana_type = "VIDEO", og da leter jeg frem video og viser det, så det er ikke tilfeldig


Jeg burde kanskje ha beskrevet denne logikken et sted, men den er altså følgende:

- sjekk europeana_type 
- sjekk om det finnes tagger som har innholdet europeana_type beskriver (TEXT, IMAGE, VIDEO eller SOUND tror jeg det er)
- vis dette

Så, hvis det er mulig å gå gjennom de du har funnet som ikke vises med video og sjekke om 
a) sjekke om europeana_type er satt til VIDEO
b) sjekke om de har en gyldig video-link i abm_videoUri


Så kan det være vi kan lukke denne og gå rett på #133

**Comment by havardgj** [comment]
Da er det tilstrekkelig logikk - og bedre å bruke tid på #133
