### ISSUE TITLE
Utvide visning av data fra Kulturminnesøk - Riksantikvaren

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#135]
Bildetekst i formatet Bildetekst: zxxx (der denne finnes)
Bildelisens i formatet Bildelisens:yyy (der denne finnes)

Art (lokalitetsart)
Ansvarlig organisasjon
Lisens for tekst/metadata (NLOD – http://data.norge.no/nlod/no) - statisk info

Venter på ny spørring og oppdatering av innhold tilgjengelig i SPARQL endpoint

![ra_imgdetails](https://cloud.githubusercontent.com/assets/8926528/10307586/6041bdb8-6c30-11e5-8e27-dd2b06472add.png)

**Comment by atlefren** [comment]
@havardgj Du skriver: "Lisens for tekst/metadata statisk info", betyr dette at det ikke er informasjon som kommer fra APIet, men som vi vet gjelder alt fra dette APIet?

**Comment by havardgj** [comment]
Ja - dette kan jeg gjerne legge på i template


27. okt. 2015 kl. 09.30 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


@havardgj<https://github.com/havardgj> Du skriver: "Lisens for tekst/metadata statisk info", betyr dette at det ikke er informasjon som kommer fra APIet, men som vi vet gjelder alt fra dette APIet?

**Comment by atlefren** [comment]
Eventuelt kan vi la datasettene ta en parameter som er "faste" properties på alle features. Så legger vi disse på i kode og man kan behandle dem som vanlige parametere i templates etc. Det vil bli mer gjenbrukbart, og skal ikke ta så veldig lang tid. Men, opp til deg

**Comment by atlefren** [comment]
@havardgj har vi fått ny spørring her?

**Comment by havardgj** [comment]
I forhold til lisens så vet jeg så langt kun om dette tilfellet, så da tror jeg ikke det er hensiktsmessig å lage det gjenbrukbart. Kravene kan fort endre seg, f.eks. statisk, men knyttet til kategori eller noe sånt. 

Når det gjelder spørring så har vi selve spørringen, men ett av feltene har ikke noe fornuftig innhold ennå. Har purret og de skal sjekke med en gang når dette kommer. Skulle vært klart for ca. en uke siden.

**Comment by atlefren** [comment]
Got you, da tar vi det hardkoda i template enn så lenge.

Er det noe vits å implementere før vi har bekreftet at data er på plass? Eller blir det fare for dobbeltarbeid etc da?

**Comment by havardgj** [comment]
Det er nok best å vente til alt er på plass.

27. okt. 2015 kl. 15.05 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


Got you, da tar vi det hardkoda i template enn så lenge.

Er det noe vits å implementere før vi har bekreftet at data er på plass? Eller blir det fare for dobbeltarbeid etc da?

**Comment by atlefren** [comment]
@havardgj har det skjedd noe mer her?

**Comment by havardgj** [comment]
Har purret, men dessverre ikke fått beskjed om at de siste nødvendige endringer er deployet ennå.

Den 5. nov. 2015 kl. 09.53 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


@havardgj<https://github.com/havardgj> har det skjedd noe mer her?

-

**Comment by havardgj** [comment]
Denne spørringen skal nå være riktig, men det ser dessverre ikke ut til at det er innhold for alle feltene ennå - de jobber med feilsøking. Men siden tiden er litt knapp, så er det kanskje likevel mulig å legge inn spørringen og ta høyde for innhold i alle felt?


select distinct ?id ?name ?description ?loccatlabel ?locartlabel ?orglabel ?img (SAMPLE(?point) as ?point) ?url ?picture ?picturelabel ?picturedescription ?picturelicence {
?id a ?type ;
  rdfs:label ?name ;
<https://data.kulturminne.no/askeladden/schema/beskrivelse> ?description ;
<https://data.kulturminne.no/askeladden/schema/lokalitetskategori> ?loccat ;
<https://data.kulturminne.no/askeladden/schema/lokalitetsart> ?locart ;
<https://data.kulturminne.no/askeladden/schema/AnsvarligOrganisasjon> ?org ;
?p <https://data.kulturminne.no/difi/geo/kommune/1601> ;
<https://data.kulturminne.no/askeladden/schema/geo/point/etrs89> ?point .
optional { ?loccat rdfs:label ?loccatlabel .}
optional {  ?locart rdfs:label ?locartlabel .}
optional {   ?org rdfs:label ?orglabel .}
BIND(REPLACE(STR(?id), "https://data.kulturminne.no/askeladden/lokalitet/", "") AS ?lokid)
BIND(bif:concat("http://www.kulturminnesok.no/kulturminnesok/kulturminne/?LOK_ID=", ?lokid) AS ?url)
optional {
?picture <https://data.kulturminne.no/bildearkivet/schema/lokalitet> ?id .
?picture <https://data.kulturminne.no/schema/source-link> ?link .
?picture rdfs:label ?picturelabel .
?picture dc:description ?picturedescription .
?picture <https://data.kulturminne.no/bildearkivet/schema/license> ?picturelicence .
BIND(REPLACE(STR(?id), "https://data.kulturminne.no/askeladden/lokalitet/", "") AS ?lokid)
BIND(bif:concat("http://kulturminnebilder.ra.no/fotoweb/cmdrequest/rest/PreviewAgent.fwx?ar=5001&sz=600&rs=0&pg=0&sr=", ?lokid) AS ?img)
  }
}

**Comment by atlefren** [comment]
Har fått spørringen for kommune på plass, skal gå i gang med template nå.

Ser dog at jeg ikke kan SPARQL-spørrespråket godt nok enda til å klare å lage en lignende spørring for fylke. 

Her er eksisterende spørring for fylke: https://gist.github.com/atlefren/a8b0ec68453a78644c00 har du @havardgj mulighet for å bistå (eller skaffe bistand) til å få denne til å fungere for nye atributter også?

**Comment by havardgj** [comment]
Tror dette da blir riktig spørring:

select distinct ?id ?name ?description ?loccatlabel ?locartlabel ?orglabel ?img (SAMPLE(?point) as ?point) ?url ?picture ?picturelabel ?picturedescription ?picturelicence {
?id a ?type ;
rdfs:label ?name ;
<https://data.kulturminne.no/askeladden/schema/beskrivelse> ?description ;
<https://data.kulturminne.no/askeladden/schema/lokalitetskategori> ?loccat ;
<https://data.kulturminne.no/askeladden/schema/lokalitetsart> ?locart ;
<https://data.kulturminne.no/askeladden/schema/AnsvarligOrganisasjon> ?org ;
<https://data.kulturminne.no/askeladden/schema/i-kommune> ?kommune ;
<https://data.kulturminne.no/askeladden/schema/geo/point/etrs89> ?point .
optional { ?loccat rdfs:label ?loccatlabel .}
optional {  ?locart rdfs:label ?locartlabel .}
optional {   ?org rdfs:label ?orglabel .}
BIND(REPLACE(STR(?id), "https://data.kulturminne.no/askeladden/lokalitet/", "") AS ?lokid)
BIND(bif:concat("http://www.kulturminnesok.no/kulturminnesok/kulturminne/?LOK_ID=", ?lokid) AS ?url)
optional {
?picture <https://data.kulturminne.no/bildearkivet/schema/lokalitet> ?id .
?picture <https://data.kulturminne.no/schema/source-link> ?link .
?picture rdfs:label ?picturelabel .
?picture dc:description ?picturedescription .
?picture <https://data.kulturminne.no/bildearkivet/schema/license> ?picturelicence .
BIND(REPLACE(STR(?id), "https://data.kulturminne.no/askeladden/lokalitet/", "") AS ?lokid)
BIND(bif:concat("http://kulturminnebilder.ra.no/fotoweb/cmdrequest/rest/PreviewAgent.fwx?ar=5001&sz=600&rs=0&pg=0&sr=", ?lokid) AS ?img)
  }
FILTER regex(?kommune, "^.*08[1-9]{2}") .
}

?kommune er lagt til og et filter på de to første siffer i kommunenummer - som er fylkesnummer - i dette tilfellet 08 (Telemark)

**Comment by atlefren** [comment]
Flott, da skal jeg teste den

Preview på visningen:

![image](https://cloud.githubusercontent.com/assets/1829927/11438398/e28d8d1e-94f4-11e5-94fb-8798cd3e2700.png)

**Comment by atlefren** [comment]
Skal fungere nå

Demo på 

http://knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=riksantikvaren&komm=1601&layer=norges_grunnkart_graatone&geomFilter=true&showGeom=true#11/63.4098/10.3644

og

http://knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=riksantikvaren&fylke=1&layer=norges_grunnkart_graatone&geomFilter=true&showGeom=true#9/59.2797/11.2413

**Comment by havardgj** [comment]
Ser bra ut. Ett spørsmål og ett problem:

- Betyr det at det også er tatt høyde for lokalitetsart og AnsvarligOrganisasjon og at disse vil vises om det finnes innhold? Vet at RA har problemer med at data for noen felt har "falt ut", så det kan være at det er grunnen, men jeg kan altså ikke se noen eksempler på at disse feltene vises.

- Det ser ut til å være et problem med lokaliteter med bilder - der returneres det nå flere objekt for samme lokalitet - en for hvert bilde - men bilde URL er den samme for alle. Dette tror jeg må fikses i selve spørringen - jeg sjekker med RA.

**Comment by atlefren** [comment]
1. lokalitetsart og AnsvarligOrganisasjon har jeg ikke gjort noe med, de lå ikke inne på skissa di, så jeg overså dem. Hvis du har et forslag til utforming på disse skal jeg se på en løsning for å vise disse hvis de finnes.

2. Ja, sannsynligvis er dette noe med spørringene. Fint om du sjekker opp dette

**Comment by havardgj** [comment]
1. Beklager at de ikke var i skissa. Det jeg tenkte var at de kunne vises under og med samme format som type. Lisens kan vises med ekstern lenke som i flere av de andre templatene.

2. I påvente av en fullgod løsning der vi kun får ett objekt for hver lokalitet, så er det mulig å justere spørringen til å i alle fall vise ulike bilder for hver av de lokalitetene som returneres. De to linjene med BIND... kan byttes ut til:

BIND(REPLACE(STR(?link), "http://kulturminnebilder.ra.no/fotoweb/default.fwx\\?search\\=", "") AS ?linkid)
BIND(bif:concat("http://kulturminnebilder.ra.no/fotoweb/cmdrequest/rest/PreviewAgent.fwx?ar=5001&sz=600&rs=0&pg=0&sr=", ?linkid) AS ?img)

**Comment by atlefren** [comment]
Så dette er altså feltene

locartlabel -> lokalitetsart 
orglabel -> AnsvarligOrganisasjon
og lisens er statisk: "(NLOD – http://data.norge.no/nlod/no)"

**Comment by havardgj** [comment]
Ja

**Comment by atlefren** [comment]
Da skal det meste være på plass!
