### ISSUE TITLE
Optimalisere og verifisere rekkefølge for lasting

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#138]
Sjekke at objekter lastes på mest mulig optimal måte og at det ikke finnes unødvendige avhengigheter

- Ved lasting av rute kan det se ut til at visning av splashscreen venter på henting av selve rutedata og behandling av disse - se /demonstratorer/flyktningeruta.html

**Comment by atlefren** [comment]
- Her har jeg forsikret meg om at splash-screen åpner seg umiddelbart, og har lagt til en spinner som viser at data laster
	- Fint med tilbakemelding på: 
		1. Fungerer det som forventet?
		2. Hvordan fungerer det på ulike enheter

**Comment by havardgj** [comment]
Prioritering av splash-screen fungerer fint. Men siden en allerede har en spinner i kartvisningen, så lurer jeg på om det skaper mer uro enn nytte å ha en spinner også på splash-screen. Den sier jo ikke noe om det en ser på, og hvis en går inn på kartet før informasjonen er lastet så får en den spinneren en "trenger". Og hvis en bruker litt tid på splash-screen og ikke går inn på kart før innholdet faktisk er lastet - så er den på en måte overflødig.

**Comment by atlefren** [comment]
Skjønner, da er det fjernet og denne er klar for re-test

**Comment by havardgj** [comment]
Fungerer bra.
