### ISSUE TITLE
Teste Leaflet plugin for lokal caching av kartfliser

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#140]
https://github.com/MazeMap/Leaflet.TileLayer.PouchDBCached

**Comment by atlefren** [comment]
Har lagt inn biblioteket og avhengigheter, samt satt useCache på alle kart fra kartverket

Demo på http://development.atlefren-kulturraadet.divshot.io/demonstratorer/config.html?datasets=&bbox=2.4609375%2C56.9449741808516%2C33.3984375%2C71.85622888185527&layer=norges_grunnkart_graatone#9/63.2052/10.6155

Ser ut til å fungere fint i firefox ihvertfall

**Comment by havardgj** [comment]
I Safari får jeg opp dialogboks om å tillate lagring lokalt svært mange ganger for en visning. Selv om jeg velger tillat. I Chrome fungerer det veldig bra. Er det evt. enkelt å bare enable for enkelte nettlesere i stedet for å bruke for mye tid på feilsøking?



27. okt. 2015 kl. 14.18 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


Har lagt inn biblioteket og avhengigheter, samt satt useCache på alle kart fra kartverket

Demo på http://development.atlefren-kulturraadet.divshot.io/demonstratorer/config.html?datasets=&bbox=2.4609375%2C56.9449741808516%2C33.3984375%2C71.85622888185527&layer=norges_grunnkart_graatone#9/63.2052/10.6155<http://development.atlefren-kulturraadet.divshot.io/demonstratorer/config.html?datasets=&bbox=2.4609375,56.9449741808516,33.3984375,71.85622888185527&layer=norges_grunnkart_graatone#9/63.2052/10.6155>

Ser ut til å fungere fint i firefox ihvertfall

**Comment by atlefren** [comment]
Hmm, slik nettleser-sjekking kan jo være knotete, men jeg skal se om det finnes en smart løsning for å komme seg rundt. Har spurt utvikleren bak om han har vært borti problemet.

**Comment by atlefren** [comment]
Dette er visst en kjent feil https://github.com/MazeMap/Leaflet.TileLayer.PouchDBCached/issues/6

**Comment by atlefren** [comment]
Testet å legge inn en sjekk på safari, men har ikke noe nettleser å teste med

**Comment by havardgj** [comment]
Ser ut til å fungere fint i Safari nå - ingen advarsel og filer hentes fra http://opencache.statkart.no
