### ISSUE TITLE
Utvide Flickr API til å støtte grupper

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#141]
https://www.flickr.com/services/api/flickr.groups.pools.getPhotos.html
https://www.flickr.com/photos_user_map.gne?path=kulturminnesok&nsid=&mode=group

**Comment by atlefren** [comment]
Har en første versjon på denne

http://knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=kulturminnesok_flickr&bbox=2.4609375%2C56.9449741808516%2C33.3984375%2C71.85622888185527&layer=norges_grunnkart_graatone#5/65.44/17.9297


Dog, et er en del ting jeg ikke er 100% fornøyd med

1. Gruppe-apiet støtter ikke filtering på boundingbox eller radius. Dvs vi må hente alle
2. Det er relativt mange bilder i en gruppe (1300 i denne), og apiet lar oss kun hente 500 pr kall. Dermed får vi 3 kall etter hverandre
3. Av de 1300 bildene har kun ca 300 posisjon, dette er ikke mulig å filtrere i API-kallet
4. group_id er en litt "kryptisk" ID på formen 1426230@N24 (som går igjen i urlen her https://www.flickr.com/groups/1426230@N24)

**Comment by havardgj** [comment]
Synes dette ser veldig bra ut - gitt forutsetningene som du har listet opp under. Det er veldig fint å ha dette som en mulighet, men ser at uthenting basert på brukerid nok er den sikreste og mest aktuelle løsningen i de fleste tilfeller.
