### ISSUE TITLE
Utvide posisjoneringsfunksjonalitet til å følge bruker

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#142]
Ved bruk av Leaflet Locate eller tilsvarende plugin

**Comment by atlefren** [comment]
- Denne skal nå fungere, kan være noe småprik igjen, nærmere bestemt
		- la knappen være en "toggle" med av/på state
		- Teste bedre med faktisk mobil-gps
		- Sjekk hvis man beveger seg utenfor område
