### ISSUE TITLE
Vise faktisk bounding box i kartmodul i generator

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#143]
Vis faktisk bounding box i kartmodulen. Mulighet for å endre størrelse på denne uavhengig av zooming i kart. Vise boks uavhengig av proporsjoner for kartmodulen der den vises.

**Comment by atlefren** [comment]
Har nå laget en versjon på denne, kan testes på http://knreise.github.io/demonstratorer/demonstratorer/generator.html

**Comment by havardgj** [comment]
Ser ut til å fungere bra. Testet i Safari og Chrome.

27. okt. 2015 kl. 13.16 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


Har nå laget en versjon på denne, kan testes på http://knreise.github.io/demonstratorer/demonstratorer/generator.html
