### ISSUE TITLE
Teste å bytte fra bitmap til vektorbaserte ikoner for punkt

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#144]
Så nært som samme ikoner som i dag som mulig, men med mulighet for å sette farge i kode - uten å være låst til ikonene som nå finnes i Leaflet.awesome-markers

**Comment by atlefren** [comment]
Har gjort et forsøk på å fikse awesome-markers til å benytte en "egenlaget" SVG-marker. Det blir rimelig likt: 

![image](https://cloud.githubusercontent.com/assets/1829927/10517149/ce2629f4-735b-11e5-9756-326368b3df62.png)


Koden på http://development.atlefren-kulturraadet.divshot.io/ bruker nå SVG-markers, må teste noe på de faktiske demonstratorene før det merges.

Repo for nye biblioteket: https://github.com/knreise/Leaflet.knreise-markers

**Comment by havardgj** [comment]
Dette ser veldig lovende ut - og helt enig i at det visuelle er mer enn likt nok. Har ikke fått testet så mye, men ser at de flytter seg litt ved første klikk.

15. okt. 2015 kl. 16.44 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


Har gjort et forsøk på å fikse awesome-markers til å benytte en "egenlaget" SVG-marker. Det blir rimelig likt:

[image]<https://cloud.githubusercontent.com/assets/1829927/10517149/ce2629f4-735b-11e5-9756-326368b3df62.png>

Koden på http://development.atlefren-kulturraadet.divshot.io/ bruker nå SVG-markers, må teste noe på de faktiske demonstratorene før det merges.

Repo for nye biblioteket: https://github.com/knreise/Leaflet.knreise-markers

**Comment by atlefren** [comment]
Dette med flyttinga skal jeg se på, når det gjelder skyggen er nok det en bug. Jobber videre med denne

**Comment by atlefren** [comment]
@havardgj Skal nå ha fikset "hoping" og skygger. Fint om du tester litt mer

**Comment by havardgj** [comment]
Har testet med Safari, Chrome og Firefox på desktop og Safari på iOS - ser ut til å fungere utmerket.


19. okt. 2015 kl. 12.41 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


@havardgj<https://github.com/havardgj> Skal nå ha fikset "hoping" og skygger. Fint om du tester litt mer
