### ISSUE TITLE
Ikke mulig å velge datasett i generator med IE 11

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#146]
Klikk registreres ikke og datasett bytter ved klikk plass i lista

**Comment by atlefren** [comment]
Tror dette skyldes at vi bruker https://github.com/voidberg/html5sortable/ for å kunne sortere lista, men det er kanskje ikke så mye behov for å kunne sortere? Det virker uansett rart å sortere siden datasettene ligger i et grid. 

Jeg tror det fort kan svies av mye tid på å prøve å fikse kombinasjonen sortering og klikk i IE.

**Comment by havardgj** [comment]
Tror ikke sortering er noe poeng nå, nei. Så hvis det gjør ting enklere og mer robust hvis denne muligheten fjernes, så er det bare å gjøre det.

14. okt. 2015 kl. 17.42 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


Tror dette skyldes at vi bruker https://github.com/voidberg/html5sortable/ for å kunne sortere lista, men det er kanskje ikke så mye behov for å kunne sortere? Det virker uansett rart å sortere siden datasettene ligger i et grid.

Jeg tror det fort kan svies av mye tid på å prøve å fikse kombinasjonen sortering og klikk i IE.
