### ISSUE TITLE
Oppdatere API for Jernbanemuseet

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#148]
Innholdet hos Jernbanemuseet er nå strukturert i forhold til tema og det innholdet vi opprinnelig ønsket å hente ut (2. Verdenskrig) skal nå ligge i presentation 732:

`https://api.kulturpunkt.org/v2/owners/54/presentations/732`

Hente et kulturpunkt (record):
`https://api.kulturpunkt.org/v2/owners/54/groups/264/records/2576`

(Objektstruktur: owner -> group -> presentation -> record)

Det enkleste er kanskje å utvide APIet til å kunne sende inn presentation ID som parameter, og la det være default som i dag?

Demonstrator for 2. verdenskrig kan oppdateres med nytt parameter.

**Comment by atlefren** [comment]
Sliter litt med denne, det ser ikke ut som om presentations inneholder posisjon:


her er responsen vi har nå:
![image](https://cloud.githubusercontent.com/assets/1829927/10430793/704d3a0e-7101-11e5-90a9-f0462a80b267.png)


Her er respons med presentation:
![image](https://cloud.githubusercontent.com/assets/1829927/10430805/8ccc79f6-7101-11e5-9aba-238b7daf4415.png)


Det aner meg at kanskje parameteret position sier noe, men jeg vet ikke hva jeg skal spørre med dette mot for å få posisjon. Har også testet urlen https://api.kulturpunkt.org/v2/owners/54/presentations/732/geography men denne fungerer ikke.

Har du mulighet til å sjekke opp dette @havardgj  ?

**Comment by havardgj** [comment]
Har bedt om tilbakemelding fra KulturIT på dette

**Comment by jonlande** [comment]
Heisann. Nå skal du få med et 'location'-objekt på records i /presentations/<id>.

**Comment by atlefren** [comment]
@jonlande supert! Takk

@havardgj er det nå slik at alle records for presentation 732 (som vi skal bruke) ligger i group 264 (og ikkr 192 som det var tidligere)?

**Comment by jonlande** [comment]
@atlefren Det er riktig, alle records som har med 2. verdenskrig å gjøre ligger i group 264 (group 192 var bare en tilfeldig group som fantes hos Jernbanemuseet fra før)

**Comment by atlefren** [comment]
@jonlande supert, jeg antok det og det ser ut til å fungere fint!

**Comment by atlefren** [comment]
Nå er vi nok mer inne på innhold enn teknologi, men ser at de fleste records virker veldig 2.verdenskrig-relaterte, med noen unntak:

- https://api.kulturpunkt.org/v2/owners/54/groups/264/records/2702
- https://api.kulturpunkt.org/v2/owners/54/groups/264/records/2597
- https://api.kulturpunkt.org/v2/owners/54/groups/264/records/2580


Dette var de jeg fant. Er det slik det skal være?

**Comment by atlefren** [comment]
Ser også for https://api.kulturpunkt.org/v2/owners/54/groups/264/records/2617 at det er brukt ganske mye css-klasser. Det skaper trøbbel for visningen vår, eksempel:
![image](https://cloud.githubusercontent.com/assets/1829927/10457496/eceb808c-71c6-11e5-992b-0c79f49bfb6a.png)

hvis jeg manuelt fjerner alle css-klasser:

![image](https://cloud.githubusercontent.com/assets/1829927/10457502/fda61d1a-71c6-11e5-8be4-67088753bd53.png)

Jeg har lite lyst til å skrive kode som fjerner alle css-klasser, så mitt ønske er at dataene kun bruker standard html-tagger uten klasser (det blir ekstra krøll i og med at vi selv bruker bootstrap)

**Comment by atlefren** [comment]
Skal nå fungere som forventet, med unntak av dette med css. Måtte legge inn støtte for links og audio

**Comment by jonlande** [comment]
@atlefren Alle record'ene som ligger i den group'en var tagget med 2. verdenskrig (gjort av Jernbanemuseet), så da regner jeg med de hører hjemme der. Nå kan du legge på parameteren 'strip_html', for å fjerne det meste av tags og attributter (inkludert alle 'class'): https://api.kulturpunkt.org/v2/owners/54/groups/264/records/2617?strip_html=true. Si fra hvis jeg tar bort for lite/mye :)

**Comment by atlefren** [comment]
@jonlande ja, vi får la de som kan fag styre med fag :)

Fantastisk at du svarer og kommer opp med løsninger, skal teste i løpet av dagen og gi tilbakemelding!

**Comment by atlefren** [comment]
Ser bedre ut nå:

![image](https://cloud.githubusercontent.com/assets/1829927/10479006/9eb7db9a-7261-11e5-84e2-db59b018fa46.png)


![image](https://cloud.githubusercontent.com/assets/1829927/10479031/b9cdaacc-7261-11e5-8b00-da6d76c913d5.png)

**Comment by havardgj** [comment]
Ser ut til å fungere veldig bra. Justeringer av innhold og objekter som returneres knyttet til dette temaet følges opp separat.
