### ISSUE TITLE
Generell støtte for linje i generator

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#151]
- Støtte for full URL for rute fra ut.no - eks: http://ut.no/tur/2.3397/
- Beholde støtte for kortformat som i dag
- Legge på http://crossorigin.me/ i kode for URL-er til linjefil
- Støtte URL til filer på følgende format: KML, GPX og GeoJSON (gjort)
- Feilmelding om URL ikke blir gjenkjent med støttet filendelse

**Comment by atlefren** [comment]
Tester: 

[ ] KML: http://knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=&allstatic=true&buffer=2&linecolor=%230033ff&line=http%3A%2F%2Fridewithgps.com%2Froutes%2F6273486.kml&layer=norges_grunnkart_graatone
[ ] GeoJSON: http://knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=&allstatic=true&buffer=2&linecolor=%230033ff&line=http%3A%2F%2Fknreise.no%2Fdata%2Fkystlinje.geojson&layer=norges_grunnkart_graatone
[ ] GPX-fil: http://knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=&allstatic=true&buffer=2&linecolor=%230033ff&line=http%3A%2F%2Fridewithgps.com%2Froutes%2F6273486.gpx&layer=norges_grunnkart_graatone
[ ] GPX fra ut.no: http://knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=&allstatic=true&buffer=2&linecolor=%230033ff&line=http%3A%2F%2Fut.no%2Ftur%2F2.3397%2Fgpx&layer=norges_grunnkart_graatone

**Comment by atlefren** [comment]
Merk at linje fra ut.no kan legges til på formen http://ut.no/tur/2.3397/gpx (med /gpx på slutten)
