### ISSUE TITLE
Feil i 3D-visning fra demonstrator

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#153]
- Ikke alltid riktig kartgrunnlag som brukes (se skjembilde) 
http://localhost:8080/demonstratorer/config_3d.html?datasets=arkeologi&komm=438&layer=norges_grunnkart_graatone&geomFilter=true&showGeom=true
<img width="1345" alt="skjermbilde 2015-10-08 08 55 17" src="https://cloud.githubusercontent.com/assets/8926528/10359698/48e6f644-6d9b-11e5-8221-a563db10350b.png">

- Noe ser ut til å henge seg ved valg av Wikipedia som kilde (http://localhost:8080/demonstratorer/config_3d.html?datasets=arkeologi%2Cwikipedia&komm=438&layer=norges_grunnkart_graatone&geomFilter=true&showGeom=true)

**Comment by atlefren** [comment]
Ah.
Jeg har forklaringer på begge, spørsmålet er hvordan vi løser det:

1. Kartlag: For 2d-kart bruker vi tilecahe (xyz) fra kartverket, for 3d bruker vi WMTS (litt grunnet hva som er støttet i de forskjellige bibliotekene). Kartverket har ikke alle kartlagene som er tilgjengelig som tilecache tilgjengelig som WMTS. Derfor har jeg lagt inn en "fallback" til norges_grunnkart i farger.
Løsningsforslag:
- Se om en nyere versjon av cesium støtter xyz-tilecacher, da blir ting "likt"
- Gi brukeren en feilmelding hvis kartet ikke er tilgjengelig
- ta høyde for dette i generator

2. Problemet her er at for 3d-kart har vi ikke noe dynamisk lasting av data mens bruker zoomer/panorerer, vi henter alle data ved oppstart. Du har laget et kart som resulterer i en spørring mot wikipedia med for stor radius. Det fører til en feil som kræsjer alt.
løsningsforslag:
- ikke la løsningen dø i stillhet, men si fra til bruker
- skrive om for å hente data ved zoom/pan, men dette tror jeg kan bli komplekst

**Comment by havardgj** [comment]
3. Høres greit ut. Dette er en bonus-feature, og det er ikke noe problem om det bare fungerer med noen kartlag. Kanskje en også kunne lagt inn en liten tekst ved 3D-checkboxen også med info om hvilke kart en kan bruke? 

6. Ignorere evt. feil og gi beskjed til adminbruker? F.eks. informasjon om at Wikipedia ikke (alltid) fungerer ved checkbox for 3D? Tror kanskje det blir forvirrende for en sluttbruker å få en melding om dette.

**Comment by atlefren** [comment]
Har gjort som forespurt. Det er kun "norges grunnkart gråtone" som ikke fungerer, så har lagt til en advarsel om denne, i tillegg kommer det opp en advarsel om de datasettene som har satt en "minZoom"

![image](https://cloud.githubusercontent.com/assets/1829927/10842264/c6821136-7ef0-11e5-9bb8-52c4c0b79dac.png)

Hvis en feil oppstår i 3d-visning lastes bare ikke datasettet, men det logges en error til console

**Comment by havardgj** [comment]
Ser bra ut. Men siden de fleste nok vil bruke vanlig 2D-kart så får kanskje advarselen litt mye fokus? Hadde det vært mulig å legge inn logikk slik at denne boksen kun vises når checkbox for 3D er avkrysset?

**Comment by atlefren** [comment]
Det skal være mulig

**Comment by atlefren** [comment]
@havardgj Da er det på plass
