### ISSUE TITLE
Add target if embedded

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#156]
Detect if map is embedded in web-page, and add target="_blank" to source link in detail view.

**Comment by atlefren** [comment]
Assuming you mean emnedded as in "placed in a iFrame?" Then this seems like a good guideline: http://stackoverflow.com/questions/326069/how-to-identify-if-a-webpage-is-being-loaded-inside-an-iframe-or-directly-into-th

**Comment by havardgj** [comment]
Yes - placed in IFrame would probably be the way this is done. Solution does not need to be 100% if a fairly simple solution can cover most browsers. 

Typical example here: http://www.kulturradet.no/arskonferansen-2015/historisk-kart-over-harstad

<img width="733" alt="skjermbilde 2015-10-12 15 25 11" src="https://cloud.githubusercontent.com/assets/8926528/10428982/6fb2c46c-70f5-11e5-9b9f-736c7271060b.png">

**Comment by atlefren** [comment]
fixed, demo on: http://knreise.github.io/demonstratorer/experiments/iframe.html


adds target="_blanks" to links in sidebar and splash screen"

**Comment by havardgj** [comment]
Ser ut til å fungere bra.
