### ISSUE TITLE
Henting av Wikipedia-artikler henger seg

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#158]
http://localhost:8080/demonstratorer/2verdenskrig.html#7/59.3444/12.2827:wikipedia_93650

<img width="1124" alt="skjermbilde 2015-10-13 19 33 06" src="https://cloud.githubusercontent.com/assets/8926528/10462873/5e42b22c-71e1-11e5-965c-5d275acff4c7.png">

Ser ut til å fungere her:
http://knreise.no/demonstratorer/demonstratorer/2verdenskrig.html#8/60.649/8.4375:wikipedia_93650

**Comment by atlefren** [comment]
Dette skyldes en følgefeil fra #148, fikset nå
