### ISSUE TITLE
Enkle "howtos"

### ISSUE THREAD

**Issue by atlefren** [knreise/demonstratorer#164]
- [x] Sette opp datasett basert på CartoDB-tabell
- [x]  Sette opp nytt datasett i API - ikke detaljert instruks for selve mappingen, men en sjekkliste for hvilke filer som trengs og prosessen rundt

**Comment by havardgj** [comment]
- [ ] Sette opp nytt datasett i API - ikke detaljert instruks for selve mappingen, men en sjekkliste for hvilke filer som trengs og prosessen rundt

**Comment by atlefren** [comment]
Datasett i API: https://github.com/knreise/KNReiseAPI/blob/master/add_dataset.md

**Comment by atlefren** [comment]
Cartodb: https://github.com/knreise/demonstratorer/wiki/add-new-dataset-from-cartodb

**Comment by havardgj** [comment]
Denne ser veldig grundig og bra ut.

En detalj - i listen over forventede attributter står det nå images - skulle det vært image?

Jeg har ellers prøvd å sette opp et par tabeller - en med litt innhold fra NRK og en med innhold fra Nasjonalbiblioteket. CartoDB-tabellen nrk_norge_rundt fungerer fint, mens tabellen bygdebok_telemark bare henger seg. Har satt opp kode der det eneste jeg endrer er tabellnavnet. Kan du se hva det skyldes?


29. okt. 2015 kl. 17.28 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


Cartodb: https://github.com/knreise/demonstratorer/wiki/add-new-dataset-from-cartodb

**Comment by havardgj** [comment]
Lurer på om feilen med bygdebok-tabellen kan skyldes at noen av radene ikke hadde punkt-data (the_geom)? Og at det forårsaker en feil som ikke var håndtert? Har i alle fall funnet noen slike rader, oppdatert i tabellen og får dem nå opp i kartet.

**Comment by atlefren** [comment]
Ja, det kan fort være, jeg satt nettopp opp denne, og det fungerte fint

http://codepen.io/atlefren/pen/zvadPG

**Comment by atlefren** [comment]
det skal være images faktisk ;), den forventer å få enten en liste bilder eller et bilde, kanskje litt forvirrende, men skal fungere
