### ISSUE TITLE
Liste over kommuner ikke sortert helt alfabetisk

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#167]
Kommuner som begynner på ÆØÅ i generator kommer ikke helt riktig i lista

**Comment by atlefren** [comment]
Til den som måtte lure:

Jeg brukte ORDER BY i SQL for å sortere lista, denne spørringen ble kjørt på CartoDb. Cartodb kjører Postgres, postgres sorterer med "collation". Norsk er ikke default, og man kan ikke overstyre dette (så vidt jeg vet). Dermed vil ORDER by returnere feil.

Løsningen er å sortere i JavaScript: http://jstips.logdown.com/posts/308083-javascript-tips-17-locale-aware-sort
