### ISSUE TITLE
Emneord i generator fungerer ikke

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#168]
Emneordene fungerer ikke helt og havner nå sammen med datasett - f.eks.:

http://knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=difo%3Aemne&komm=104&layer=norges_grunnkart_graatone&geomFilter=true&showGeom=true

**Comment by atlefren** [comment]
Skjønner ikke helt hva du mener her. Funksjonaliteten er ikke endret.

Jeg har tolket denne som at hvis du velger datasett difo og emne krigshistorie får du et kartlag som er objekter fra datasett difo med emneord krigshistorie.

Det fungerer fint her: http://knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=difo%3Akrigshistorie&komm=104&layer=norges_grunnkart_graatone&geomFilter=true&showGeom=true#12/59.4639/10.6615


I eksempelet ditt har du brukt emneord "emne", det finnes ikke og man får dermed ikke treff. 

Er det jeg som misforstår her?

**Comment by havardgj** [comment]
Ser at eksempelet var litt uklart. Symptomet var at emneord ikke fungerte her http://knreise.no/demonstratorer/demonstratorer/generator.html . Trodde emneorde skulle inn som et eget parameter og ikke "sammen med" dataset-parameteret. Men ser at det nå fungerer på http://knreise.github.io/demonstratorer/demonstratorer/generator.html og at den teorien var litt dårlig.
