### ISSUE TITLE
Feil i Dovre-demo

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#169]
Lurer på om det er noe feil med oppsettet for Dovre - det som nå ligger på http://knreise.github.io/demonstratorer/demonstratorer/dovre.html

Får den ganske konsevent til å henge seg ved litt zooming og panorering? Testet i Chrome.

<img width="1917" alt="pastedgraphic-2" src="https://cloud.githubusercontent.com/assets/8926528/11095251/60443054-8894-11e5-82a8-01867d1e5453.png">

**Comment by atlefren** [comment]
ja, får samme feilen her. 

Skal se på det i morgen tidlig!
