### ISSUE TITLE
Justere spørringer for kulturminner (Riksantikvaren)

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#174]
Legge til linje i spørring som gjør at en kun får unike lokaliteter. Spørringen som brukes nå gir flere lokalitetsobjekter hvis det finnes flere bilder. 

Ny spørring med ny linje markert:

select distinct ?id ?name ?description ?loccatlabel ?locartlabel ?orglabel ?img (SAMPLE(?point) as ?point) ?url ?link ?linkid ?picturelabel ?picturedescription ?picturelicence {
?id a ?type ;
  rdfs:label ?name ;
<https://data.kulturminne.no/askeladden/schema/beskrivelse> ?description ;
<https://data.kulturminne.no/askeladden/schema/lokalitetskategori> ?loccat ;
<https://data.kulturminne.no/askeladden/schema/lokalitetsart> ?locart ;
<https://data.kulturminne.no/askeladden/schema/AnsvarligOrganisasjon> ?org ;
?p <https://data.kulturminne.no/difi/geo/kommune/1601> ;
<https://data.kulturminne.no/askeladden/schema/geo/point/etrs89> ?point .
optional { ?loccat rdfs:label ?loccatlabel .}
optional {  ?locart rdfs:label ?locartlabel .}
optional {   ?org rdfs:label ?orglabel .}
BIND(REPLACE(STR(?id), "https://data.kulturminne.no/askeladden/lokalitet/", "") AS ?lokid)
BIND(bif:concat("http://www.kulturminnesok.no/kulturminnesok/kulturminne/?LOK_ID=", ?lokid) AS ?url)
optional {
<b>{select sample(?picture) as ?picture ?id where {?picture <https://data.kulturminne.no/bildearkivet/schema/lokalitet> ?id}}</b>
?picture <https://data.kulturminne.no/bildearkivet/schema/lokalitet> ?id .
?picture <https://data.kulturminne.no/schema/source-link> ?link .
?picture rdfs:label ?picturelabel .
?picture dc:description ?picturedescription .
?picture <https://data.kulturminne.no/bildearkivet/schema/license> ?picturelicence .
BIND(REPLACE(STR(?link), "http://kulturminnebilder.ra.no/fotoweb/default.fwx\\?search\\=", "") AS ?linkid)
BIND(bif:concat("http://kulturminnebilder.ra.no/fotoweb/cmdrequest/rest/PreviewAgent.fwx?ar=5001&sz=600&rs=0&pg=0&sr=", ?linkid) AS ?img)
  }
}

**Comment by atlefren** [comment]
@havardgj har du eksempel på en kommune som har objekter med mer enn et bilde?

**Comment by havardgj** [comment]
Trondheim (1601) skal ha en del.

**Comment by atlefren** [comment]
@havardgj Hmmm, med denne spørringen https://sparql.kulturminne.no/?default-graph-uri=&query=select+distinct+%3Fid+%3Fname+%3Fdescription+%3Floccatlabel+%3Flocartlabel+%3Forglabel+%3Fimg+%28SAMPLE%28%3Fpoint%29+as+%3Fpoint%29+%3Furl+%3Flink+%3Flinkid+%3Fpicturelabel+%3Fpicturedescription+%3Fpicturelicence+%7B%0D%0A%3Fid+a+%3Ftype+%3B%0D%0Ardfs%3Alabel+%3Fname+%3B%0D%0A<https%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Fbeskrivelse>+%3Fdescription+%3B%0D%0A<https%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Flokalitetskategori>+%3Floccat+%3B%0D%0A<https%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Flokalitetsart>+%3Flocart+%3B%0D%0A<https%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2FAnsvarligOrganisasjon>+%3Forg+%3B%0D%0A%3Fp+<https%3A%2F%2Fdata.kulturminne.no%2Fdifi%2Fgeo%2Fkommune%2F1601>+%3B%0D%0A<https%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Fgeo%2Fpoint%2Fetrs89>+%3Fpoint+.%0D%0Aoptional+%7B+%3Floccat+rdfs%3Alabel+%3Floccatlabel+.%7D%0D%0Aoptional+%7B+%3Flocart+rdfs%3Alabel+%3Flocartlabel+.%7D%0D%0Aoptional+%7B+%3Forg+rdfs%3Alabel+%3Forglabel+.%7D%0D%0ABIND%28REPLACE%28STR%28%3Fid%29%2C+"https%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Flokalitet%2F"%2C+""%29+AS+%3Flokid%29%0D%0ABIND%28bif%3Aconcat%28"http%3A%2F%2Fwww.kulturminnesok.no%2Fkulturminnesok%2Fkulturminne%2F%3FLOK_ID%3D"%2C+%3Flokid%29+AS+%3Furl%29%0D%0Aoptional+%7B%0D%0A%7Bselect+sample%28%3Fpicture%29+as+%3Fpicture+%3Fid+where+%7B%3Fpicture+<https%3A%2F%2Fdata.kulturminne.no%2Fbildearkivet%2Fschema%2Flokalitet>+%3Fid%7D%7D%0D%0A%3Fpicture+<https%3A%2F%2Fdata.kulturminne.no%2Fbildearkivet%2Fschema%2Flokalitet>+%3Fid+.%0D%0A%3Fpicture+<https%3A%2F%2Fdata.kulturminne.no%2Fschema%2Fsource-link>+%3Flink+.%0D%0A%3Fpicture+rdfs%3Alabel+%3Fpicturelabel+.%0D%0A%3Fpicture+dc%3Adescription+%3Fpicturedescription+.%0D%0A%3Fpicture+<https%3A%2F%2Fdata.kulturminne.no%2Fbildearkivet%2Fschema%2Flicense>+%3Fpicturelicence+.%0D%0ABIND%28REPLACE%28STR%28%3Flink%29%2C+"http%3A%2F%2Fkulturminnebilder.ra.no%2Ffotoweb%2Fdefault.fwx%5C%5C%3Fsearch%5C%5C%3D"%2C+""%29+AS+%3Flinkid%29%0D%0ABIND%28bif%3Aconcat%28"http%3A%2F%2Fkulturminnebilder.ra.no%2Ffotoweb%2Fcmdrequest%2Frest%2FPreviewAgent.fwx%3Far%3D5001%26sz%3D600%26rs%3D0%26pg%3D0%26sr%3D"%2C+%3Flinkid%29+AS+%3Fimg%29%0D%0A%7D%0D%0A%7D&format=text%2Fhtml&timeout=0&debug=on ser det ikke ut som om noen av "img"-feltene har mer enn en bildelink?

**Comment by havardgj** [comment]
Oppdatering over telefon - ser bra ut.
