### ISSUE TITLE
Mulighet for visning av bilde i fullskjerm-format

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#176]
I første om gang for bilder knyttet til lokaliteter fra Riksantikvaren. Ikon på bilde for å vise at zoom er mulig. Fra detaljvisning. Ved klikk - vise bilde i fullskjermsvisning - skalert til tilgjengelig nettleserstørrelse. Ved klikk på bilde - lukke og returner til detaljvisning.

I bilde-URL er sz attributt for høyde i pixler - eks: http://kulturminnebilder.ra.no/fotoweb/cmdrequest/rest/PreviewAgent.fwx?ar=5001&sz=600&rs=0&pg=0&sr=T365_01_0085

**Comment by atlefren** [comment]
Denne skal nå være løst, sammen med #175 og #174
