### ISSUE TITLE
Justering for fullskjermvisning

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#179]
Om det er mulig å finne litt tid til sånt - noen justeringer for fullskjem-visningen av bilder:
- Sentrere bilde
- Svak gjennomsiktighet for sort bakgrunn (opacity 0.9)
- Knapp for å lukke - kun visuelt. Klikk på selve bildet og bakgrunn må også lukke som i dag.
![fullskjem](https://cloud.githubusercontent.com/assets/8926528/12328477/d6d24d40-badb-11e5-9128-5901cd2c1823.jpg)

**Comment by atlefren** [comment]
![image](https://cloud.githubusercontent.com/assets/1829927/12333964/909c3cc0-baf7-11e5-949d-dcf00fc2cd24.png)

Relativt greit dette, eneste jeg ikke fant ut av var horisontal sentrering, vet ikke hvor viktig det er? Brukte 10 min på dette, så kan nok sette av litt mer tid

**Comment by havardgj** [comment]
Ser bra ut. Men det er vertikal sentrering du tenker på som ikke er løst? Bruk gjerne litt mer tid på det - tror det egentlig skal være ganske greit. Alternativt kan du peke meg i riktig retning i CSS-en så kan jeg eksperimentere litt herfra.

**Comment by atlefren** [comment]
vertikal sentrering ja. Skal være løst nå
