### ISSUE TITLE
Justering av SPARQL-spørring

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#180]
Det har blitt oppdaget at Nidaros-domen mangler i denne løsningen... Det viser seg at den rett og slett mangler beskrivelse. Det jobbes med å finne ut av hvor den har blitt av, men det ser ut til at det samme gjelder ca. 10.000 andre kulturminner. Spørringen som brukes krever beskrivelse, og selv om det jobbes med å få på plass data, så hadde det vært fint om dette feltet kunne gjøres OPTIONAL. 

I spørringene som brukes mot Riksantikvarens SPARQL-API må en derfor endres

Fra
<https://data.kulturminne.no/askeladden/schema/beskrivelse> ?description ;
til
optional { ?id <https://data.kulturminne.no/askeladden/schema/beskrivelse> ?description .}

Denne linja må også flyttes ned til de feltene som nå er optional (?loccatlabel, ?locartlabel og ?orglabel)

**Comment by atlefren** [comment]
skal være fikset

**Comment by havardgj** [comment]
Ser bra ut - da er Nidarosdomen med oss igjen
