### ISSUE TITLE
Feil ved visning av bakgrunnskart - IE 11

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#181]
http://knreise.github.io/demonstratorer/demonstratorer/config.html?datasets=riksantikvaren&bbox=2.4609375,56.9449741808516,33.3984375,71.85622888185527&layer=norges_grunnkart_graatone#14/63.429/10.385

Ser sånn ut med IE 11
![image001-1](https://cloud.githubusercontent.com/assets/8926528/12579400/f69949b2-c427-11e5-9d13-a8851fb7e4a1.png)

Ser ut til å fungere fint i andre nettlesere

**Comment by atlefren** [comment]
hmm.. Fungerer med ie11 her...

kan du teste å ta opp developer tools (f12) og sjekke i console-tabben om det dukker opp noen feil der?

**Comment by havardgj** [comment]
Med Mac er jeg så heldig at jeg slipper IE - videresender til den som rapporterte

**Comment by havardgj** [comment]
Ser at det fungerer på andre maskiner med IE 11 her også - så da graver vi videre. Ingen feil i console der det ikke fungerer.

**Comment by atlefren** [comment]
det er ikke noe "compatibility mode"?

**Comment by havardgj** [comment]
Det viste seg være cache-relatert. Ser det er litt rom for bedre testing før ting flagges, ja...
