### ISSUE TITLE
Option to display scale

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#182]
Option in map configuration to show standard Leaflet scale. Hide scale as default. Use default values for the scale display (http://leafletjs.com/reference.html#control-scale) apart from for imperial scale - hide this scale value.

**Comment by atlefren** [comment]
Implemented, the parameter ```showScaleBar``` can be set to true in the options to KR.setupMap, as shown here: https://github.com/knreise/demonstratorer/blob/master/demonstratorer_content/trondheim.js#L96

Ducumented at https://github.com/knreise/demonstratorer/blob/master/api_doc.md
