### ISSUE TITLE
Do not allow full screen view of images for all datasets

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#183]
The current option to view images from Riksantikvaren (SPARQL) in a full screen view seems to work fine - an expand icon is displayed and on click the image is displayed full screen on a dark background. 

For other datasets the expand icon is not displayed, but a click on the image displays full screen dark background with a broken image. 

Simple solution? 
Disable click on images to full screen view for all datasets apart from riksantikvaren

More flexible solution? 
Allow the spesification of hires image as a separate attribute and diplay expand icon and allow click for all items that have a value for hires image

**Comment by atlefren** [comment]
Fixed

Actually: the more flexible solution was implemented (but with a bug). This is why the expand icon wasn't displayed. A bug caused the background to appear on click.
