### ISSUE TITLE
Feil ved visning av Folketellingsdata

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#185]
http://localhost:8080/demonstratorer/config.html?datasets=folketelling&komm=301&layer=norges_grunnkart_graatone&geomFilter=true&showGeom=true#15/59.8778/10.8655

Detaljvisningen blir stående og spinne

![skjermbilde 2016-03-03 13 12 50](https://cloud.githubusercontent.com/assets/8926528/13493971/bd2cc7f8-e141-11e5-8dda-f25bd550248d.png)

**Comment by atlefren** [comment]
@havardgj  prøv med http://localhost:8080/demonstratorer/config.html?datasets=folketelling&komm=0301&layer=norges_grunnkart_graatone&geomFilter=true&showGeom=true#15/59.8778/10.8655

istedenfor?

Ser ut som om CartoDb-spørringen ikke klarer å finne kommune 301, mens 0301 går fint. 

Mest interessant er hvordan du bygde opp denne urlen?

**Comment by havardgj** [comment]
med 0301 fungerer det fint, ja. URL er bygget opp med generatoren - Oslo som område og Folketelling 1910 som datasett. 

Problemet er kanskje da at kommuner hentes fra en tabell i CartoDB og at kolonnen for kommunenummer er satt til å være "number" og at 0 som første siffer da forsvinner...?

**Comment by atlefren** [comment]
Ja, det ser ut som om spørringen min mot cartodb returnerer en int for kommunenummer, da blir det jo følgefeil. 

Trodde jeg hadde fikset dette før, men skal gjøre en fiks i generatoren
