### ISSUE TITLE
Utvalg basert på kommune og fylke fungerer ikke

### ISSUE THREAD

**Issue by atlefren** [knreise/demonstratorer#191]
Utvalg basert på kommune og fylke fungerer ikke – viser hele landet når du begynner å flytte eller zoome i kartene (gjelder flere (alle?) datasett)
( - men utvalg basert på linjegeometri fungerer)

**Comment by atlefren** [comment]
Klarer ikke gjenskape denne med telemark-demonstratoren ihvertfall.

Konkrete eksempler på datasett/konfigurasjoner dette ikke fungerer på?

**Comment by RaCaoKmp** [comment]
Hei!
Her har vi vært "sloppy" i vår beskrivelse av problematikken! Sorry!!
Det det dreier seg om er "lag ditt eget kart" og valg av kommune/fylke der! Linje virker OK og bounding-boks har jeg ikke testet. Men... når jeg drar opp min lokale versjon av din "refactor" build og går inn i "Lag ditt eget kart" og velger en kommune eller et fylke samt et eller flere datasett så virker ikk avgrensningen på kommune/fylke fungere. Ser OK.-ish ut når du først kommer inn på siden (men savner en "markering" i kartet av valgt kommune/fylke slik det er på "skarp" versjon) men om du begynner å flytte deg eller zoome in/ut så vises kartet data som ligger utenfor den valgte kommunen/fylket (se skjermdump med "Asker" kommune valgt). Håper dette forklarer issuen bedre?
![image](https://user-images.githubusercontent.com/10845721/37510771-8ced7f4c-28fc-11e8-8fb0-b3ba84b470e0.png)

**Comment by RaCaoKmp** [comment]
Sjekkede bounding-boks akkurat nå og denne fungerer ikke heller ser det ut som.

**Comment by atlefren** [comment]
løst med https://github.com/knreise/demonstratorer/pull/213
