### ISSUE TITLE
Tydeligere markering av hvilket objekt som har fokus / er valgt 

### ISSUE THREAD

**Issue by atlefren** [knreise/demonstratorer#195]
ref #193

**Comment by atlefren** [comment]
Jeg tenker at denne løses ved å ikke bruke grønnfargen for riksantikvaren-datasett, eller skurrer dette fortsatt?

**Comment by RaCaoKmp** [comment]
Ja, kanskje, vet ikke. Vi opplever det som at der er litt vanskelig å skille hvilken polygon/objekt som har fokus blant alle de andre. Kan man få til en slags "ramme" rundt den polygon/objekt som er i fokus? Som skiller det objektet fra den andre som ligger i kartet?

**Comment by atlefren** [comment]
løst i #220
