### ISSUE TITLE
Annen farge på punktene, både for lokalitetene og for enkeltminnene

### ISSUE THREAD

**Issue by atlefren** [knreise/demonstratorer#196]
Annen farge på punktene, både for lokalitetene og for enkeltminnene (if. Farge på polygon over). I tillegg må vi tydeligere skille på disse to (dvs. lokaliteter kontra enkeltminner) slik at de ikke er så like. Forslagsvis kunne man kanskje bruke den opp-og-nedvendte triangelen som brukes på kulturminnesøk som symbol for enkeltminnene (eller noe lignende) ref #193

**Comment by atlefren** [comment]
Ønsker feedback her:

1. Pr nå har punkter for lokaliteter samme farge som flatene (brun). Blir dette rett?
2. Hvis vi bruker triangel for enkeltminner: gir det mening å bruke samme farge?

**Comment by RaCaoKmp** [comment]
1. Brun farge for Lokalitetene blir OK!
2. Om vi kan få triangler så kan nog samme farge fungere. Det viktige er at skille det fra punktene for Lokalitetene i from. Hvis ikke triangler så en annen fomr/type som klart skiller seg fra Lok-punktene

**Comment by atlefren** [comment]
Løst i #210
