### ISSUE TITLE
Visning av metadata – lokalitetsnivå (for Kulturminner og Kulturmiljøer)

### ISSUE THREAD

**Issue by atlefren** [knreise/demonstratorer#197]
<med ledetekst og rekkefølge på felter>
-  [x]	Tittel
-  [ ]	Bilde(r) - Tilsvarende visning som f.eks. Digitalt fortalt (gjerne med bildetekst – om mulig) 
    -  [ ] Samt Vise både «Kulturminnebilder» og 
    -  [ ] «Brukerbilder» (når nytt API er på plass) for hvert kulturminne
- [x]	Kategori
- [x]	Art
- [ ]	Datering – må aggregeres fra Enkelminne-nivå (hvis mulig?) med label «flere dateringer», hvis flere dateringer på enkeltminne-nivå (jf.  visningen i Kulturminnesøk)
- [ ]	Vernestatus – må aggregeres fra Enkelminne-nivå (hvis mulig?) med label «Ulike vernestatus», hvis flere vernestatuser på enkeltminne-nivå (jf. Kulturminnesøk)
- [ ]	Tekst – f.eks inntil 300 tegn (inkl mellomrom), med « … » for å indikere at det finnes mere tekst. Tekst fra feltet Kulturminnesøk-beskr (om den finnes, ellers Askeladden-beskr)
- [x]	lenke til original visning

**Comment by atlefren** [comment]
Her gjelder samme spørsmål om tekst, samt at jeg er litt usikker på hvor enkelt det er å få på plass denne aggregeringen, men skal gjøre et forsøk

**Comment by RaCaoKmp** [comment]
Teksten må hentes via eget oppslag mot eget API for Lokaliteter http://kart.ra.no/arcgis/rest/services/Distribusjon/Kulturminner/MapServer/10 (Feltet "Beskrivelse" er Askeladden-beskr. og "Kulturminnesøk" er Kulturminnesøk-beskr.), respektive Kulturmiljøer http://kart.ra.no/arcgis/rest/services/Distribusjon/Kulturminner/MapServer/9

Om aggregeringen er en svært vanskelig ting så vent med den!

**Comment by atlefren** [comment]
Skjønner!

Men, jeg sliter litt med dette APIet

Jeg har en lokasjon, Oslo fengsel, med LokalitetID: 164085

så bygger jeg følgende spørring (basically where LokalitetID IN (164085) )

http://kart.ra.no/arcgis/rest/services/Distribusjon/Kulturminner/MapServer/10/query?where=LokalitetID+IN+%2888460%29&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&f=pjson

Men responsen sier meg lite:
```
{
 "displayFieldName": "LID",
 "fieldAliases": {
  "LID": "LID"
 },
 "fields": [
  {
   "name": "LID",
   "type": "esriFieldTypeString",
   "alias": "LID",
   "length": 30
  }
 ],
 "features": [
  {
   "attributes": {
    "LID": "164085"
   }
  }
 ]
}
```
Er det jeg som gjør noe feil, eller er dette en respons som sier meg at det ikke finnes noen beskrivelse?

**Comment by RaCaoKmp** [comment]
Du må spørre etter beskrivelse respektive Kulturminnesøk også (fra Christer her hos oss). Så her: http://kart.ra.no/arcgis/rest/services/Distribusjon/Kulturminner/MapServer/10/query?where=LokalitetID+IN+%2888460%29&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=Beskrivelse%2C+Kulturminnesok&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&f=pjson

**Comment by atlefren** [comment]
Glimrende, så da blir det riktigste å spørre på både Beskrivelse og Kulturminnesok

http://kart.ra.no/arcgis/rest/services/Distribusjon/Kulturminner/MapServer/10/query?where=LokalitetID+IN+%28164085%29&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=Beskrivelse%2CKulturminnesok&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&f=pjson

**Comment by RaCaoKmp** [comment]
Tenker det?! Tanken er at om vi har tekst i Kulturminnesøk-beskr. så viser vi den (mer formidlingsrettet vanligvis) men om vi ikke har det så viser vi Askeladden-beskr.. Hvis vi ikke har noe - "so be it"! Men dette får du avgjøre hva som er mest hensiktsmessig i relasjon til ytelse og koding

**Comment by atlefren** [comment]
Det høres ut som en plan.

Men, det er alltid noen utfordringer:

ta LokalitetID: 164829

Denne har følgende Kulturminnesøk-beskr ("Kulturminnesok");
"Beskrivelse ikke registrert"

Men Askeladden-beskr ("Beskrivelse") er:
"Kgl.res murgård. Leiegård, som også har adr Hollendergt 10. Brann i nr. 55 i jan/feb 2000"

**Comment by RaCaoKmp** [comment]
Ja, livet! Shit in - shit out! Vi kjør på simple stupid - dvs. først KMSØK-beskr., har vi ikke den beskr. fra Askeladden. Så er dataene som dataene er!

**Comment by atlefren** [comment]
beskrivelse løst i https://github.com/knreise/demonstratorer/pull/211

**Comment by atlefren** [comment]
Aggrering flyttet til #212
