### ISSUE TITLE
Visning av metadata – enkeltminnenivå  

### ISSUE THREAD

**Issue by atlefren** [knreise/demonstratorer#198]
med ledetekst og rekkefølge på felter

-	Tittel
-	Enkeltminnekategori
-	Enkeltminneart
-	Datering
-	Vernestatus
-	Tekst – f.eks inntil 300 tegn (inkl mellomrom), med « … » for å indikere at det finnes mere tekst. Tekst fra Askeladden-beskr.
-	lenke til original visning

**Comment by atlefren** [comment]
Såvidt jeg klarer å se er alt unntatt tekst på plass her:

![image](https://user-images.githubusercontent.com/1829927/37511551-818a9d12-28ff-11e8-8d36-02355b9760ba.png)

Spørsmålet er hvordan jeg henter ut teksten? Blir det et eget oppslag mot et API, eller skal dette ligge på responsen jeg allerede får? @RaCaoKmp

**Comment by RaCaoKmp** [comment]
Ser bra ut! Teksten må hentes via eget oppslag mot eget API http://kart.ra.no/arcgis/rest/services/Distribusjon/Kulturminner/MapServer/8 (Feltet "Beskrivelse" er Askeladden-beskr. og "Kulturminnesøk" er Kulturminnesøk-beskr.)

**Comment by atlefren** [comment]
Løst i https://github.com/knreise/demonstratorer/pull/211
