### ISSUE TITLE
Rydde i Demonstratorsiden 

### ISSUE THREAD

**Issue by atlefren** [knreise/demonstratorer#199]
Vi ønsker følgende liste:
- [x]	Norge 
  - [x] (kulturminner/kulturmiljøer må være med)
- [x]	Telemark (kulturminner/kulturmiljøer må være med)
  - [x] (kulturminner/kulturmiljøer må være med)
- [x] Trondheim kommune (ny med samme datagrunnlag som Nidelva)
- [x] Gudbransdalsleden (fjernes)
- [x] Dovre (fjernes)
- [x] Turistvegen over Følgefonna (fjernes)
- [x] Flyktingeruten gjennom Østmarka til Sverige 
  - [x] (+ brukerminner/-bilder når nytt API er oppe)
- [x] Brudleruta mellom Sirdal og Kvenesdal (fjernes)
- [x] Nidelva (må ses på)
  - [x] - KML-file trigges ikke 
  - [x] kulturminner/kulturmiljøer må være med)
- [x] Akerselva (fjernes)
- [x]	Historiske bensinstasjoner (as is)
- [x]	Ny Demonstrator (Kulturminnedata fra Riksantikvaren) som bør vise følgende objekter som egne separate kartlag
  - [x]	Arkeologiske kulturminner – kategori = <Arkeologisk minne»
  - [x]	Kirkesteder – kategori = <Kirkested»
  - [x]	Bebyggelse – kategori = <Bebyggelse-Infrastruktur»
  - [x]	Kulturmiljøer – kategori = <Kulturmiljøer»

**Comment by atlefren** [comment]
Ad nidelven: jeg mistenker at jeg har gal FTP-info. Jeg får logga meg på en ftp hos domeneshop, men mistenker det ikke er den som brukes mer?

**Comment by atlefren** [comment]
Ad krigens kulturminner: finnes det noen måte å begrense kulturminner til ww2-relatert stoff?)

**Comment by atlefren** [comment]
ad Kulturminnedata fra Riksantikvaren:

Litt usikker på hvordan jeg skal hente ut kategoriene "Arkeologisk minne", "Kirkested", og "Bebyggelse-Infrastruktur". 

Kulturmiljøer er vel layer 7, men de andre er kanskje et subsett av Lokaliteter?

**Comment by RaCaoKmp** [comment]
kategoriene "Arkeologisk minne", "Kirkested", og "Bebyggelse-Infrastruktur" kan du finne som egen sub-datasett via feltet LokalitetskategoriID i APIet mener jeg. Skal dobbelsjekke!

**Comment by RaCaoKmp** [comment]
Ad Nivelva! Har sett litt i koden på den versjon av "refactor" som går på min maskin og der pekes det til line: 'http://localhost:9000/data/nidelva.kml', (i index.js filen som definerer datasetene) men denne plassering finnes ikke uten nidelv.kml filen ligger i stedet her: C:\Kart-demo\demonstratorer\public\data 
Kan det ha noe med saken å gjøre?

**Comment by atlefren** [comment]
Absolutt. Men jeg har også testet å gå mot http://www.knreise.no/miniProxy/miniProxy.php/http://knreise.no/demonstratorer/demonstratorer/nidelva.kml

Jeg har logget meg på det jeg tror er FTP for knreise.no og lagt nidelva.kml i data-katalogen, men det funker dårlig. Mistenker at jeg har feil FTP-info?

**Comment by RaCaoKmp** [comment]
Skal sjekke med Vemund på mandag! Han er hjemme med sykt barn idag. Återkommer!

**Comment by atlefren** [comment]
@RaCaoKmp 

har nå på plass kartlagene i demonstratoren "kulturminnedata":

![image](https://user-images.githubusercontent.com/1829927/37529696-11f37aee-2938-11e8-86c6-2ec18f475aee.png)
Men de burde kanskje ha separate farger?

**Comment by RaCaoKmp** [comment]
Ser finfint ut! Separate farge for de ulike kategoriene vil vi ha ja! Fin noen passende du!

**Comment by atlefren** [comment]
løst med https://github.com/knreise/demonstratorer/pull/224
