### ISSUE TITLE
Datasett: Lokalhistoriewiki - Vise de samme metadataene som Wiki-datasettene

### ISSUE THREAD

**Issue by atlefren** [knreise/demonstratorer#204]

**Comment by atlefren** [comment]
Problem:

For å få til å hente bilder og "extracts" fra wikipedia er vi avhengig av en ekstra spørring.

Når jeg kjører samme spørringen mot lokalhistoriewiki får jeg feil:

"Unrecognized values for parameter 'prop': extracts, pageimages"

Det er altså snakk om følgende spørring:
https://lokalhistoriewiki.no/api.php?action=query&prop=extracts|pageimages&exlimit=max&exintro=&pilimit=max&pageids=284974|292634|266756|25146|293119|267291|22827|293113|537|263896|127790|56020|96826|78873|96300|81049|81482|97618|19946|263936|56308|117927|202187&format=json&continue=


Dette må altså eventuelt taes med lokalhistoriewiki. Følger du evt opp @RaCaoKmp  ?

**Comment by RaCaoKmp** [comment]
Hei

Skal prøve på det!

A.

Fra: Atle Frenvik Sveen <notifications@github.com>
Sendt: torsdag 15. mars 2018 14.21
Til: knreise/demonstratorer <demonstratorer@noreply.github.com>
Kopi: Olsson, Carl Anders <carl.anders.olsson@ra.no>; Mention <mention@noreply.github.com>
Emne: Re: [knreise/demonstratorer] Lokalhistoriewiki: Vise de samme metadataene som Wiki-datasettene (#204)


Problem:

For å få til å hente bilder og "extracts" fra wikipedia er vi avhengig av en ekstra spørring.

Når jeg kjører samme spørringen mot lokalhistoriewiki får jeg feil:

"Unrecognized values for parameter 'prop': extracts, pageimages"

Det er altså snakk om følgende spørring:
https://lokalhistoriewiki.no/api.php?action=query&prop=extracts|pageimages&exlimit=max&exintro=&pilimit=max&pageids=284974|292634|266756|25146|293119|267291|22827|293113|537|263896|127790|56020|96826|78873|96300|81049|81482|97618|19946|263936|56308|117927|202187&format=json&continue=<https://lokalhistoriewiki.no/api.php?action=query&prop=extracts%7Cpageimages&exlimit=max&exintro=&pilimit=max&pageids=284974%7C292634%7C266756%7C25146%7C293119%7C267291%7C22827%7C293113%7C537%7C263896%7C127790%7C56020%7C96826%7C78873%7C96300%7C81049%7C81482%7C97618%7C19946%7C263936%7C56308%7C117927%7C202187&format=json&continue=>

Dette må altså eventuelt taes med lokalhistoriewiki. Følger du evt opp @RaCaoKmp<https://github.com/racaokmp> ?

**Comment by RaCaoKmp** [comment]
Har fått et navn på ansvalig/utvikler for Lokalhistorisk Wiki og kontakter vedkommende i morgen. Så får vi se?!

**Comment by RaCaoKmp** [comment]
Sent av gårde spørsmål om dette til Lokalhistoriske wiki/NB, har fått foreløpig kontakt men avventer ytterligere info.

**Comment by atlefren** [comment]
lukket i https://github.com/knreise/demonstratorer/pull/226
