### ISSUE TITLE
Datasett: Arkeologi - Erstatte med nytt datasett fra Riksantikvaren 

### ISSUE THREAD

**Issue by atlefren** [knreise/demonstratorer#205]
Erstatte med nytt datasett fra Riksantikvaren (Kulturminnedata fra Riksantikvaren) inklusive bilder fra RA og bilder fra brukerbilder/Kulturminnesøk på Askeladdenobjekter (nytt API) Utvalg basert på tema; tilsvarende som f.eks. DiMu og Musit
- utvalg basert på <Lokalitetsart>
- dialogboks «Lokalitetsart»

**Comment by RaCaoKmp** [comment]
Hei! Tanken er at erstatte det gamle "arkeologi"-datasettet med vårt nye datasett fra Askeladden (Lokaliteter og Kulturmiljøer med bilder fra Askeladden respektive Kulturminnebilder)

I tillegg ønsker vi et annet helt "nytt" datasett med brukerminner og brukerbilder. Første del av dette APIet (brukerminner) blir ferdig før testing i neste uke (du blir første mann så kom med feedback på hva som fungerer og ikke). Deretter tas et tilsvarende API for brukerbildene frem.

**Comment by atlefren** [comment]
Ok, bare for å oppklare:

Datasett-gruppen "Arkeologi" skal bestå av
- lokaliteter fra http://kart.ra.no/arcgis/rest (med bilder fra https://kulturminnebilder.ra.no)
- Kulturmiljøer fra http://kart.ra.no/arcgis/rest (med bilder fra https://kulturminnebilder.ra.no)
- brukerminner fra http://beta.ra.no/api/brukerminner (med bilder fra nytt API)

Spørsmålet blir da det samme som på #218, skal vi gjøre noe filtrering her? (cc @RaCaoKmp)

**Comment by RaCaoKmp** [comment]
Njaa! 
Datasett-gruppen "Kulturminnedata fra Riksantikvaren" (det du kaller "Arkeologi" se mine kommentarer over) skal bestå av:
- Lokaliteter fra http://kart.ra.no/arcgis/rest (med bilder fra https://kulturminnebilder.ra.no **OG** bilder på Askeladden-objekter fra det nye brukerbilde-APIet som er under utvikling)
- Kulturmiljøer fra http://kart.ra.no/arcgis/rest (med bilder fra https://kulturminnebilder.ra.no **OG** bilder på Askeladden-objekter fra det nye brukerbilde-APIet som er under utvikling)
Dette datasett vil vi gjerne skal ha utvalg basert på dialogboks «Lokalitetsart» (slik at du kan filtrere på ulike Lok-arter - helst mulighet at velge flere(?) 

I tillegg vil vi ha et nytt "eget" datasett som heter "Brukerminner fra Kulturminnesøk" som skal bestå av:
-Brukerminner fra http://beta.ra.no/api/brukerminner (med bilder fra nytt API som er under utvikling)

Håper dette er klargjørende? Hvis ikke bare spør i vei igjen!

**Comment by RaCaoKmp** [comment]
Nja (igjen)!
Det er snakk om tre ting det er riktig, men vi snakker ikke om de tre samme tingene.
1. Endring av det som er definert som arkeologi i dag der dette erstattes av Innføring av en ny gruppe (Kulturminnedata fra Riksantikvaren (dvs dine 1 og 2 er samme oppgave/ting - se tabell i oppgave 10 i vårt originale dokument)
2. Datasettene fra http://kart.ra.no/arcgis/rest skal kunne hente bilder fra to ulike APIer? Jeg regner med at dette gjelder all bruk av disse datasettene, ikke bare i konteksten av grupperingen Kulturminnedata fra Riksantikvaren (riktig! slik vil vi helst ha det! - dvs. din 3 er min 2 )
3. I tillegg vil vi ha et nytt "eget" datasett som heter "Brukerminner fra Kulturminnesøk" som skal bestå av Brukerminner fra http://beta.ra.no/api/brukerminner (med bilder fra nytt API som er under utvikling - dvs min nye 3 som jeg prøvde å forklare i kommentaren over, se også tabell i oppgave 10 i vårt originale dokument)

Tre ting er det! Bare spør (eller klag) om det fortsatt er uklart!

**Comment by atlefren** [comment]
Da henger jeg med!

Slik jeg tolker det er da 

1. Denne oppgaven her
2. En ny oppgave jeg ikke har registrert
3. Allerede løst i https://github.com/knreise/demonstratorer/issues/206 med untak av brukerbilder (som er beskrevet i https://github.com/knreise/demonstratorer/issues/216)

Jeg lukker denne oppgaven og oppretter en ny, slik at vi (jeg) har oversikt

**Comment by atlefren** [comment]
Denne erstattes av #222,  #216 og #216
