### ISSUE TITLE
Alternativ kilde for kulturminner

### ISSUE THREAD

**Issue by atlefren** [knreise/demonstratorer#26]
Hente data fra Riksantikvaren via det nye SPARQL-grensesnittet.

Har fått eksempelspørring, det som må gjøres er:

- Utvide apiet med støtte for spørring
- parse resultat
- transformere koordinater

**Comment by havardgj** [comment]
Spørring som gir alle relevante felt for hele Telemark i JSON-format. Tar litt tid og må nok optimaliseres. Sjekk av bildelenker er ikke på plass.

https://sparql.kulturminne.no/?default-graph-uri=&query=SELECT+%3Flokid+%3Flabel+%3Fbeskrivelse+%3Flokalitetsartlab+%3Floklab+%3Fpunkt+%3Fomraade+%3Flokimg%0D%0Awhere+%7B%0D%0A%3Flok+a+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2FLokalitet%3E+.%0D%0A%3Flok+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E+%3Flabel+.%0D%0A%3Flok+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Fi-kommune%3E+%3Fkommune+.%0D%0A%3Flok+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Fbeskrivelse%3E+%3Fbeskrivelse+.%0D%0A%3Flok+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Flokalitetsart%3E+%3Flokalitetsart.%0D%0A%3Flokalitetsart+rdfs%3Alabel+%3Flokalitetsartlab.%0D%0A%3Flok+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Flokalitetskategori%3E+%3Flokalitetskategori.%0D%0A%3Flokalitetskategori+rdfs%3Alabel+%3Floklab+.%0D%0A%3Flok+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Fgeo%2Fpoint%2Fetrs89%3E+%3Fpunkt+.%0D%0A%3Flok+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Fgeo%2Farea%2Fetrs89%3E+%3Fomraade.%0D%0AFILTER+regex%28%3Fkommune%2C+%22%5E.*05%5B1-9%5D%7B2%7D%22%29+.%0D%0ABIND%28REPLACE%28STR%28%3Fkommune%29%2C+%22http%3A%2F%2Fpsi.datanav.info%2Fdifi%2Fgeo%2Fkommune%2F%22%2C+%22%22%29+AS+%3Fkommuneid%29%0D%0ABIND%28REPLACE%28STR%28%3Flok%29%2C+%22https%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Flokalitet%2F%22%2C+%22%22%29+AS+%3Flokid%29%0D%0ABIND%28bif%3Aconcat%28%22http%3A%2F%2Fkulturminnebilder.ra.no%2Ffotoweb%2Fcmdrequest%2Frest%2FPreviewAgent.fwx%3Far%3D5001%26sz%3D400%26rs%3D0%26pg%3D0%26sr%3D%22%2C+%3Flokid%29+AS+%3Flokimg%29%0D%0A%7D%0D%0A&format=application%2Fsparql-results%2Bjson&timeout=0&debug=on

**Comment by atlefren** [comment]
Har laget en API-wrapper for denne i API-prosjektet: https://github.com/knreise/KNReiseAPI/pull/1

Eneste problemet er at sparql-siden ikke støtter [CORS][cors], løser det for nå ved å la den gå via http://crossorigin.me/, men dette er ikke en optimal løsning. Har du @havardgj mulighet til å høre med riksantikvaren om de kan få støtte for CORS?

[cors]: http://en.wikipedia.org/wiki/Cross-origin_resource_sharing

**Comment by havardgj** [comment]
Spørsmål er sendt til Riksantikvaren - som sikkert må sende det videre til Bouvet.

**Comment by yonyonson** [comment]
Hei! Det er Bouvet folk her :) Vi ser på dette, det er sysadmin hos RA som kommer å fikse det for oss.

**Comment by atlefren** [comment]
@havardgj @yonyonson Supert! Da satser jeg på at det går i orden. 

For ordens skyld: det fungerer med http://crossorigin.me, så dette er ikke en direkte showstopper, men det hadde vært mye penere å kunne gå direkte til kilden

**Comment by atlefren** [comment]
Lukker denne, CORS får komme når det kommer
