### ISSUE TITLE
Stiling av sidebar-data

### ISSUE THREAD

**Issue by atlefren** [knreise/demonstratorer#29]
Ref skisser/wireframes:

- Jeg tror det kan være lurt å ta med seg nummer/antall for det aktuelle clusteret i denne visningen. Interessant i seg selv og med på å knytte denne visningen til det man har klikket på i kartet. 
- Hvis enkelt - endre format (f.eks. farge) på clusteret som er valgt
- Gruppere punktene i listen - enten etter type eller kilde
- Angi gruppenavn eller kilde for hver gruppe
- Gjenta ikon eller bilde i liste - samme format som i kartet

![image](https://cloud.githubusercontent.com/assets/1829927/7908829/23d9ad1e-0848-11e5-9535-cd1d3e682673.png)

- Vise N av N - i tillegg til frem og tilbake
- Vise kilde over tittel
- Gruppere innhold i to grupper - tittel, bilde, lyd, video og beskrivelse som hovedinnhold og mer konteksttuell informasjon og fakta i en egen bolk
- Enkel tabellstruktur med label og innold for kontekstuelle informasjon for å aline labels og innhold
- Fast lenke til ekstern kilde med eget ikon nederst

![image](https://cloud.githubusercontent.com/assets/1829927/7908836/314d3f42-0848-11e5-83e5-3f071fcd274d.png)

![image](https://cloud.githubusercontent.com/assets/1829927/7908842/3b724e9a-0848-11e5-9096-409fd9125eec.png)

**Comment by atlefren** [comment]
Det som gjenstår nå er re-formatering av infosider for de datasettene jeg ikke har skisser på. 

Har du noen innspill her @havardgj ?

**Comment by atlefren** [comment]
Status på denne kan sees på http://development.atlefren-kulturraadet.divshot.io/demonstratorer/dovre.html

**Comment by havardgj** [comment]
![digitaltfortalt](https://cloud.githubusercontent.com/assets/8926528/8365146/8fc82720-1b8b-11e5-9a55-b3ed65580253.png)
![digitaltmuseum](https://cloud.githubusercontent.com/assets/8926528/8365148/8fce2e54-1b8b-11e5-93c7-440735d34249.png)
![musit](https://cloud.githubusercontent.com/assets/8926528/8365147/8fcdfc18-1b8b-11e5-8e7a-8b2668eacf20.png)
![riksantikvaren](https://cloud.githubusercontent.com/assets/8926528/8365150/8fd02ff6-1b8b-11e5-993a-7eb3de19efee.png)
![verneomrader](https://cloud.githubusercontent.com/assets/8926528/8365151/8fd2fcc2-1b8b-11e5-85d4-99fc614505e9.png)
![wikipedia](https://cloud.githubusercontent.com/assets/8926528/8365149/8fcf77d2-1b8b-11e5-9ba8-5c2ff99cb725.png)
