### ISSUE TITLE
Informasjon som rent konseptuelt ikke er punktfestet, men som  er knyttet til et større geografisk område eller et stedsnavn

### ISSUE THREAD

**Issue by atlefren** [knreise/demonstratorer#30]
Kan være en fin måte å gi direkte tilgang til den viktigste informasjonen for et område – uten at man må finne alle punkt og klikke seg inn på dem. Jeg har tenkt på noe av det samme i forhold til informasjon som rent konseptuelt ikke er punktfestet, men som  er knyttet til et større geografisk område eller et stedsnavn. En kunne kanskje tenke seg at en i en slik modul fikk opp f.eks. Wikipedia-informasjon for det aktuelle området – og evt. ande tilsvarende kilder? Med disse kunne en orientere seg før man valgte å gå inn på enkeltpunkt. Kanskje kombinert med viktige enkeltpunkt fra utvalgte kilder?

**Comment by havardgj** [comment]
Tror kanskje denne kan deles i to. 

Den ene løsningen tror jeg rett og slett er å vise denne typen punkter på en litt annen måte enn andre. Forslag er å bruke sirkler i stedet for den standard "spisse" kartmarkøren. Men sirkler som visuelt ellers er i slekt med de andre markørene. Her kommer det en skisse med et forslag.

Den andre er å trekke ut noen typer punkt i en egen modul. Men her er det kanskje mer snakk om at dette blant annet kan fungere bra på ikke-punktfestede data - men at den også må kunne brukes på punktfestede data. Og derfor i prinsippet ikke knyttet til denne problemstillingen?
