### ISSUE TITLE
Popup ved oppstart

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#35]
Generell funksjonalitet for konfigurerbar popup ved oppstart
- Visning av HTML-basert innhold
- Ved hver oppstart, men med mulighet for å velge å ikke vise
- Responsiv - størrelse og plassering tilpasset ulike skjerm/vindusstørrelser
- Kun vertikal scrolling

**Comment by atlefren** [comment]
![image](https://cloud.githubusercontent.com/assets/1829927/8283842/fe9270a0-18f9-11e5-89cc-fab8fd5129e2.png)

**Comment by havardgj** [comment]
Ser ba ut - og utover at innhold må på plass, så tror jeg den eneste justeringen som kunne være fin å få med er å sentrere boksen for standard nettlesere (ikke mobil). Hvis det ikke er for vanskelig eller uryddig med en egen sånn visningsregel for denne bruken av denne boksen.


22. jun. 2015 kl. 16.16 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


[image]<https://cloud.githubusercontent.com/assets/1829927/8283842/fe9270a0-18f9-11e5-89cc-fab8fd5129e2.png>

**Comment by atlefren** [comment]
Skal se på plasseringen.

Et issue er dette med tekst for demonstratorer generert via link: her vil man ikke få plass til beskrivende tekst i url, så her må man finne en annen løsning, jeg ser 2-3 muligheter

1) ikke bruke denne informasjonen for link-generte sider
2) bruke et verktøy ala github gists eller noe slikt for å skrive beskrivelse, link i url
3) ha et sett ferdigdefinerte beskrivelser man kan velge på, evt beskrivelser pr datasett som flettes sammen og presenteres

Hva tror du @havardgj ?

**Comment by havardgj** [comment]
Jeg er usikker på om det er en prioritert feature i denne omgang å ha en slik popup for demonstratorer generert via link. Her tror jeg scenariet mest sannsynlig er at dette er satt i en kontekst av de som skal bruke denne funksjonaliteten. Og hvis en skulle gjøre det så tror jeg kanskje heller en får gjøre det mulig å hente inn innhold etter en mal fra en ekstern fil.

Når det gjelder det visuelle for de som settes opp uten dynamisk link, så tror jeg sentrering hadde vært fint. I tillegg lurer jeg på om en enkel overlay bak denne boksen (sort med gjennomsiktighet) kan være en bra måte å gi denne fokus og skille den fra resten av innholdet.


[cid:B0861AE9-DEF3-426E-9979-D15B1948E5C0@adm.kulturrad.no]
25. jun. 2015 kl. 10.51 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


Skal se på plasseringen.

Et issue er dette med tekst for demonstratorer generert via link: her vil man ikke få plass til beskrivende tekst i url, så her må man finne en annen løsning, jeg ser 2-3 muligheter

1) ikke bruke denne informasjonen for link-generte sider
2) bruke et verktøy ala github gists eller noe slikt for å skrive beskrivelse, link i url
3) ha et sett ferdigdefinerte beskrivelser man kan velge på, evt beskrivelser pr datasett som flettes sammen og presenteres

Hva tror du @havardgj<https://github.com/havardgj> ?

**Comment by havardgj** [comment]
Jeg er usikker på om det er en prioritert feature i denne omgang å ha en slik popup for demonstratorer generert via link. Her tror jeg scenariet mest sannsynlig er at dette er satt i en kontekst av de som skal bruke denne funksjonaliteten. Og hvis en skulle gjøre det så tror jeg kanskje heller en får gjøre det mulig å hente inn innhold etter en mal fra en ekstern fil. 

Når det gjelder det visuelle for de som settes opp uten dynamisk link, så tror jeg sentrering hadde vært fint. I tillegg lurer jeg på om en enkel overlay bak denne boksen (sort med gjennomsiktighet) kan være en bra måte å gi denne fokus og skille den fra resten av innholdet.
![popup](https://cloud.githubusercontent.com/assets/8926528/8351419/7bed581e-1b2d-11e5-88ba-f1662931fb24.png)

**Comment by atlefren** [comment]
Da skal det være på plass, legger ut snart. Tenker at bilde er en konfigurering, har bare benyttet en "dummy-bilde-tjeneste" nå

![image](https://cloud.githubusercontent.com/assets/1829927/8352831/638b9e74-1b38-11e5-9d3b-047f68e3f96d.png)

**Comment by atlefren** [comment]
lukker denne
