### ISSUE TITLE
Datasett: Folketelling 1910

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#36]
Direkte kobling til Riksarkivets API for folketellingene 1910. I første omgang kun for uthenting og visning av bosteder - i påvente av avklaringer knyttet til om detaljvisning av leiligheter og personer skal håndteres av Norvegiana eller av responsiv visning i Digitalarkivet.

http://arkivverket.no/arkivverket/content/download/12760/123213/version/5/file/API_1910_koord.pdf

Ikke behov for logikk for håndtering av paging - minimum zoomnivå kan settes for dette datasettet for hver av de aktuelle demonstratorene.

**Comment by atlefren** [comment]
Løst her: https://github.com/knreise/KNReiseAPI/pull/2

**Comment by atlefren** [comment]
Denne er nå på plass i APIet, men ikke tatt i bruk i noen demonstratorer. Har du noen formening om hvor denne skal benyttes @havardgj?
