### ISSUE TITLE
Gjøre "layerswitcher" kollapsbar på mobil

### ISSUE THREAD

**Issue by atlefren** [knreise/demonstratorer#38]
Den tar alt for mye plass på kartet, og man burde kunne kollapse den

![image](https://cloud.githubusercontent.com/assets/1829927/7954713/5eda1c24-09d2-11e5-91b1-68aef193a846.png)

**Comment by havardgj** [comment]
Så ikke denne og lagde en egen... Forslaget er:

Knapp i stil med + / - men med meny-ikon - f.eks. http://fortawesome.github.io/Font-Awesome/icon/bars/

Ved klikk vises boksen for valg av kilder/lag. Nytt klikk for å lukke. Klikk utenfor knapp eller boks med valg lukker også. I første omgang med valg default skjult.

**Comment by atlefren** [comment]
lukker denne, løst!
