### ISSUE TITLE
Konsistent ikonbruk

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#48]
Første forsøk på å etablere et konsistent regelsett for ikoner, markører og clustere. 

I første omgang ikke bruke ikoner - kun farger for å skille ulike typer av innhold.

Punkt
- Mindre viktig enkeltpunkt, eller punkt uten (konseptuell) spesifik posisjon - sirkel
- Punkt med spesifik posisjon - punktikon
- Punkt med spesifik posisjon og bilde - bilde

Clustere
- Cluster uten bilde
- Cluster med bilde
(- Clustring uten clustring - ved ovelapp av enkeltpunkter)

Linje

Konfigurasjon for Dovre
- Digitalt fortalt - punkt og cluster med bilde - som nå
- Fangstlokaliteter - sirkel - ingen clustring
- Verneområder som nå
- Kulturminner - MUSIT - DiMu - punkt - med clustring - samme farge som fangstlokaliteter. Hvis mulig - ett felles lag/valg i meny (Historie). Evt. Kulturminner i ett og de to andre i et annet.
- Artsobservasjoner - sirkel - ingen clustring

![ikonbruk1](https://cloud.githubusercontent.com/assets/8926528/8103867/4e8ec968-102c-11e5-895e-c71525c68d71.jpg)
![ikonbruk](https://cloud.githubusercontent.com/assets/8926528/8103866/4e8e82f0-102c-11e5-8637-ecbf52e19944.jpg)

**Comment by atlefren** [comment]
Samleside som viser forhåndsdefinerte stiler i forskjellige varianter:
![image](https://cloud.githubusercontent.com/assets/1829927/8155791/0ff4f97e-1348-11e5-908c-e7461ca9ae62.png)

**Comment by atlefren** [comment]
Screenshot av implementasjon av dette
![image](https://cloud.githubusercontent.com/assets/1829927/8156631/564d62e8-134e-11e5-8778-86c189b0911e.png)

**Comment by atlefren** [comment]
lukker denne
