### ISSUE TITLE
Bruke spørring for kulturminnelokasjoner for Trondheim - med bilder

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#50]
https://sparql.kulturminne.no/?default-graph-uri=&query=select+distinct+%3Fid+%3Fname+%3Fbeskrivelse+%3Floklab+%3Fpunkt+%3Flokimg+%7B%0D%0A%3Fid+a+%3Ftype+.%0D%0A%3Fid+rdfs%3Alabel+%3Fname+.%0D%0A%3Fid+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Fi-kommune%3E+%3Fkommune+.%0D%0A%3Fid+%3Fp+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Fdifi%2Fgeo%2Fkommune%2F1601%3E+.%0D%0A%3Fid+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Fbeskrivelse%3E+%3Fbeskrivelse+.%0D%0A%3Fid+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Flokalitetskategori%3E+%3Flokalitetskategori+.%0D%0A%3Flokalitetskategori+rdfs%3Alabel+%3Floklab+.%0D%0A%3Fid+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Fgeo%2Fpoint%2Fetrs89%3E+%3Fpunkt+.%0D%0Aoptional+%7B%0D%0A%3Fpicture+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Fbildearkivet%2Fschema%2Flokalitet%3E+%3Fid+.%0D%0A%3Fpicture+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Fschema%2Fsource-link%3E+%3Flink%0D%0ABIND%28REPLACE%28STR%28%3Fid%29%2C+%22https%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Flokalitet%2F%22%2C+%22%22%29+AS+%3Flokid%29%0D%0ABIND%28bif%3Aconcat%28%22http%3A%2F%2Fkulturminnebilder.ra.no%2Ffotoweb%2Fcmdrequest%2Frest%2FPreviewAgent.fwx%3Far%3D5001%26sz%3D400%26rs%3D0%26pg%3D0%26sr%3D%22%2C+%3Flokid%29+AS+%3Flokimg%29%0D%0A%7D%0D%0A%7D&format=application%2Fsparql-results%2Bjson&timeout=0&debug=on

**Comment by atlefren** [comment]
Påbegynnt denne: fungerer for punkter, ikke polygoner (timed out)

**Comment by havardgj** [comment]
Denne spørringen gir nå unike punkt for lokasjoner i Trondheim. Den forrige ga flere punkt for noen lokasjoner fordi en lokasjon kan bestå av flere polygoner - da vil en få et punkt for hvert av disse. Men for en punktvisning så gir det ikke mening å vise mer enn ett:

https://sparql.kulturminne.no/?default-graph-uri=&query=select+distinct+%3Fid+%3Fname+%3Fbeskrivelse+%3Floklab+%3Fpunkt+%3Flokimg+%7B%0D%0A%3Fid+a+%3Ftype+.%0D%0A%3Fid+rdfs%3Alabel+%3Fname+.%0D%0A%3Fid+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Fi-kommune%3E+%3Fkommune+.%0D%0A%3Fid+%3Fp+%3Chttp%3A%2F%2Fpsi.datanav.info%2Fdifi%2Fgeo%2Fkommune%2F1601%3E+.%0D%0A%3Fid+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Fbeskrivelse%3E+%3Fbeskrivelse+.%0D%0A%3Fid+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Flokalitetskategori%3E+%3Flokalitetskategori+.%0D%0A%3Flokalitetskategori+rdfs%3Alabel+%3Floklab+.%0D%0A%7Bselect+%3Fpunkt+%7B%0D%0A%3Fid+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Fgeo%2Fpoint%2Fetrs89%3E+%3Fpunkt+.%0D%0A%7D+limit+1%7D%0D%0Aoptional+%7B%0D%0A%3Fpicture+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Fbildearkivet%2Fschema%2Flokalitet%3E+%3Fid+.%0D%0A%3Fpicture+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Fschema%2Fsource-link%3E+%3Flink%0D%0ABIND%28REPLACE%28STR%28%3Fid%29%2C+%22https%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Flokalitet%2F%22%2C+%22%22%29+AS+%3Flokid%29%0D%0ABIND%28bif%3Aconcat%28%22http%3A%2F%2Fkulturminnebilder.ra.no%2Ffotoweb%2Fcmdrequest%2Frest%2FPreviewAgent.fwx%3Far%3D5001%26sz%3D400%26rs%3D0%26pg%3D0%26sr%3D%22%2C+%3Flokid%29+AS+%3Flokimg%29%0D%0A++%7D%0D%0A%7D&format=application%2Fsparql-results%2Bjson&timeout=0&debug=on

**Comment by atlefren** [comment]
@havardgj Det er noe feil med siste spørringen din: den gir samme punkt ("POINT (244966.31790000014 6820600.0040999986)") for alle treff

**Comment by havardgj** [comment]
Ser det nå, ja - jeg sjekker.

**Comment by havardgj** [comment]
Ser at det blir feil, ja. Har tatt dette videe med Riksantikvaren.

16. jun. 2015 kl. 10.19 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


@havardgj<https://github.com/havardgj> Det er noe feil med siste spørringen din: den gir samme punkt ("POINT (244966.31790000014 6820600.0040999986)") for alle treff

**Comment by havardgj** [comment]
Ny spørring - unike lokasjoner, men uten duplikater og med riktig punkt

https://sparql.kulturminne.no/?default-graph-uri=&query=select+distinct+%3Fid+%3Fname+%3Fdescription+%3Floccatlabel+%3Fimg+%28SAMPLE%28%3Fpoint%29+as+%3Fpoint%29++%7B%0D%0A%3Fid+a+%3Ftype+%3B%0D%0A+++rdfs%3Alabel+%3Fname+%3B%0D%0A+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Fbeskrivelse%3E+%3Fdescription+%3B%0D%0A+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Flokalitetskategori%3E+%3Floccat+%3B%0D%0A+%3Fp+%3Chttp%3A%2F%2Fpsi.datanav.info%2Fdifi%2Fgeo%2Fkommune%2F1601%3E+%3B%0D%0A+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Fgeo%2Fpoint%2Fetrs89%3E+%3Fpoint+.%0D%0A%3Floccat+rdfs%3Alabel+%3Floccatlabel+.%0D%0Aoptional+%7B%0D%0A+%3Fpicture+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Fbildearkivet%2Fschema%2Flokalitet%3E+%3Fid+.%0D%0A+%3Fpicture+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Fschema%2Fsource-link%3E+%3Flink%0D%0ABIND%28REPLACE%28STR%28%3Fid%29%2C+%22https%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Flokalitet%2F%22%2C+%22%22%29+AS+%3Flokid%29%0D%0ABIND%28bif%3Aconcat%28%22http%3A%2F%2Fkulturminnebilder.ra.no%2Ffotoweb%2Fcmdrequest%2Frest%2FPreviewAgent.fwx%3Far%3D5001%26sz%3D600%26rs%3D0%26pg%3D0%26sr%3D%22%2C+%3Flokid%29+AS+%3Fimg%29%0D%0A+++%7D%0D%0A%7D%0D%0A&format=application%2Fsparql-results%2Bjson&timeout=0&debug=on

**Comment by atlefren** [comment]
tatt i bruk denne
