### ISSUE TITLE
"enkelt" grensesnitt for å bygge demonstratorer

### ISSUE THREAD

**Issue by atlefren** [knreise/demonstratorer#55]
I stedet for en løsning der en genererer kode basert på valg i en konfigurasjon - burde en kanskje begrense mulighetene i en slik løsning så mye at det er praktisk mulig å lage dette som en helt dynamisk kode? Og da bare genererer opp en URL med de nødvendige parameterne - kommune, basemap, informasjonslag og et begrenset sett med visningsvalg etc.? 

http://knreise.no/demonstrator.html?komm=1601&datasets=difo,dimu for å vise digitalt fortalt og digitalt museum for trondheim?

- Velge datasett fra en ferdigdefinert liste
- Sette farge og type markør (sirkel/thumbnail/eller markør)
- Clustring av/på
- Min zoom ?
- Kommune eller bounding box
- Bakgrunnskart
-  (enkelte datasett eller predefinerte grupper av datasett), 
- I teorien skulle man vel kanskje også kunne gi inn url til en GPX-fil? 
- Eller ID til en samling i Norvegiana
- linje (gpx: ut.no)
- linjebuffer
- farge for linje

**Comment by atlefren** [comment]
Spørsmål ( @havardgj ): Har vi noen eksempler på en "norvegiana-samling"? Eller er det det jeg har referert til som "datasett"?

**Comment by havardgj** [comment]
Dette er funksjonalitet som vi venter på i neste versjon av Norvegiana. Det vi har gjort så langt er å hente ut data fra datasett (DiMU, Musit etc.). I tillegg er det mulig i dag å gjøre søk på tvers av datasett, men med Collections så vil en kunne hente ut predefinerte sett av objekter - som da også kan komme fra ulike datasett. I prinsippet skal ikke dette være så anderledes enn det en gjør i dag og objektene en får tilbake vil være de samme. Men både for søk og Collections så må en håndtere at ulike objekt kan komme fra ulike datasett og derfor kanskje skal vises med ulike maler - hvis en ikke allerede har knyttet ting som ikonfarge og mal for detaljvisning til objekt i stedet for datasett/layer?


17. jun. 2015 kl. 12.27 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


Spørsmål ( @havardgj<https://github.com/havardgj> ): Har vi noen eksempler på en "norvegiana-samling"? Eller er det det jeg har referert til som "datasett"?

**Comment by atlefren** [comment]
Fra @havardgj: Det eneste jeg tenker på slik den er nå er om en for datasett burde ha en liste med checkbox for valg i stedet - jeg tror det kan være lurt å kunne legge inn ligg tekst for hvert datasett og da er det enklere om det er en tekstbasert liste med checkbox for hvert datasett. Det er av og til også vanskelig å få valgt kommune - lurer på om det er hvis man har klikket på en av de andre stedsvariantene?
