### ISSUE TITLE
Sidebar: gå direkte til første element i liste

### ISSUE THREAD

**Issue by atlefren** [knreise/demonstratorer#57]

**Comment by atlefren** [comment]
Spørsmål: hvilket "threshold" skal vi ha på å gå direkte til første element kontra å vise liste? Lager dette konfigurerbart, men hadde vært greit med en fornuftig default-verdi. Jeg har testet med 10, dvs er det 10 eller færre elementer i lista går man direkte til første element

**Comment by havardgj** [comment]
10 er et greit utgangspunkt. Kanskje dette også kan enables/disables for hvert datasett eller hver gruppe av datasett (eller datasett som clustres sammen)?

**Comment by atlefren** [comment]
Det er mulig, da ser jeg for meg følgende muligheter:

1) default ha dette på, med threshold (dvs alle datasett/grupper av datasett dropper liste når du har 10 eller færre elementer), med mindre du "skrur det av"
2) Default på, ikke threshold (dvs, alle datasett/grupper av datasett dropper liste uansett lengde), skrur du det av vises alltid liste
3) Default på, ikke threshold, konfigurerbart threshold
4) Default av, konfigurerbart threshold
5) default av, konfigurerbart på uten threshold

En annen mulighet er jo at man kan tenke seg følgende:

Sidebaren har en default "noListThreshold" på 10, denne brukes, med mindre man setter "noListThreshold" på et datasett/gruppe datasett, denne kan da være

- 0: viser alltid liste
- 1 -- inf: dette er threshold
- inf: viser aldri liste

Tror kanskje dette er beste løsning?

**Comment by havardgj** [comment]
Den siste varianten høres bra ut - det tror jeg gir all den fleksibilitet man i praksis trenger.


16. jun. 2015 kl. 14.26 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


Det er mulig, da ser jeg for meg følgende muligheter:

1) default ha dette på, med threshold (dvs alle datasett/grupper av datasett dropper liste når du har 10 eller færre elementer), med mindre du "skrur det av"
2) Default på, ikke threshold (dvs, alle datasett/grupper av datasett dropper liste uansett lengde), skrur du det av vises alltid liste
3) Default på, ikke threshold, konfigurerbart threshold
4) Default av, konfigurerbart threshold
5) default av, konfigurerbart på uten threshold

En annen mulighet er jo at man kan tenke seg følgende:

Sidebaren har en default "noListThreshold" på 10, denne brukes, med mindre man setter "noListThreshold" på et datasett/gruppe datasett, denne kan da være

  *   0: viser alltid liste
  *   1 -- inf: dette er threshold
  *   inf: viser aldri liste

Tror kanskje dette er beste løsning?

**Comment by atlefren** [comment]
Denne er løst som beskrevet over
