### ISSUE TITLE
Bruke flyfoto fra Norge i bilder for 3D-visning og som mulig generelt kartgrunnlag

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#61]
Fra Kartverket:

For Kultur- og naturreise er det opprettet en egen bruker i BAAT.
 

 
Adressen til WMSen til Norge i bilder er:
http://wms.geonorge.no/skwms1/wms.norgeibilder?
 
Du kan sjekke om du har tilgang ved å åpne denne linken i en nettleser:
http://wms.geonorge.no/skwms1/wms.norgeibilder?VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&SRS=EPSG:25833&BBOX=284763.58,6745426.72,287815.37,6747034.60&LAYERS=SatelliteImage,OrtofotoAlle&STYLES=&WIDTH=577&HEIGHT=304&FORMAT=image/jpeg&BGCOLOR=0xFFFFFF&TRANSPARENT=FALSE

**Comment by atlefren** [comment]
Fjernet brukernavn/passord, siden denne issue-trackeren er helt åpen

**Comment by atlefren** [comment]
Har sjekket opp litt på denne.

"gangen" ved å benytte BAAT er som følger:

1. IP til en server registreres hos SK for å generere tokens (gjort)
2. Klient spør server om token for sin IP
3. server spør BAAT-gatekeeper om token for IP
4. server returnerer token til klient
5. klient bruker token ved forespørsler til baat-gatekeeper om kart

Dog, jeg oppgav en IP-adresse til Knreise.no-serveren til SK, nå ser denne ut til å ha endret seg. Det kan tyde på at serveren til knreise.no har dynamisk IP, og ikke vil fungere med dette opplegget.

**Comment by havardgj** [comment]
Jeg kan undersøke litt mer, men slik det ser ut nå så ser det ikke ut til å være realistisk å få til et oppsett fra vår side med en server med statisk IP. Det beste er nok dessverre derfor å la denne ligge inntil videre.
