### ISSUE TITLE
Detaljvisning for folketelling

### ISSUE THREAD

**Issue by atlefren** [knreise/demonstratorer#72]
Hente ut detaljerte data for folketellingsadresse ved klikk, vise i sidebar.

* data hentes ut på formen: http://api.digitalarkivet.arkivverket.no/v1/census/1910/property/ID
* det skilles på By og land 
* for By må en hente personer pr leilighet
    * skal dette gjøres?
* det må lages "template" som dekker by og land, samt leiligheter og personer

Se http://www.arkivverket.no/arkivverket/content/download/12760/123213/version/5/file/API_1910_koord.pdf for liste over tilgjengelige atributter for de forskjellige typene

**Comment by atlefren** [comment]
Eksempel på "by-visning"
![image](https://cloud.githubusercontent.com/assets/1829927/8327865/0a66ac3e-1a6c-11e5-8ce5-bb39d4bd3e99.png)

**Comment by havardgj** [comment]
Vi avventer visning av data for leiligheter - det hadde vært fint, men har ikke høy prioritet. Det blir da to varianter av detaljvisning - en for by og en for land.
![detalj_folketelling_by](https://cloud.githubusercontent.com/assets/8926528/8330825/7e649c50-1a84-11e5-8ed9-e8a03f3f7fc8.png)
![detalj_folketelling_land](https://cloud.githubusercontent.com/assets/8926528/8330826/7e65d552-1a84-11e5-8054-4450bc619130.png)

**Comment by atlefren** [comment]
![image](https://cloud.githubusercontent.com/assets/1829927/8349970/9e2a4560-1b21-11e5-8d72-2a1203b072d0.png)

**Comment by atlefren** [comment]
![image](https://cloud.githubusercontent.com/assets/1829927/8350348/1ded9bb4-1b25-11e5-99f3-f493ffaa9cb9.png)

**Comment by atlefren** [comment]
lukker denne
