### ISSUE TITLE
Justeringer for lagvalg

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#75]
Noen forslag til justeringer for lagvelger
- flytte boks til under knapp - slik at knappen ikke flytter seg ved klikk
- sette farge på checkbox til samme farge som markørene i kart
- spinner for lasting av hvert enkelt lag? (samme farge som checkbox?)
- visning av overlay (ikon) ved timeout eller feil - over checkbox

![layerselector](https://cloud.githubusercontent.com/assets/8926528/8365413/4764b8de-1b8d-11e5-8bec-3eca91c840b5.png)

**Comment by atlefren** [comment]
Ekspandert:
![image](https://cloud.githubusercontent.com/assets/1829927/8426436/055d8d72-1f10-11e5-883e-a34a6ac3f123.png)



Kollapset med feil:
![image](https://cloud.githubusercontent.com/assets/1829927/8426419/df321d66-1f0f-11e5-83dd-cc3e6221dbc4.png)

Ekspandert med feil: 

![image](https://cloud.githubusercontent.com/assets/1829927/8426423/eb8d7b8c-1f0f-11e5-82ea-28a8b837c4ef.png)

**Comment by atlefren** [comment]
med spinner
![image](https://cloud.githubusercontent.com/assets/1829927/8426464/1e9fe47e-1f10-11e5-8041-8a896c1a2f54.png)

**Comment by atlefren** [comment]
lukker denne, avventer respons
