### ISSUE TITLE
Flytting av navigasjon mellom detaljvisninger

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#76]
Lurer på om headeren for detaljvisningen blir litt trang - det er litt mye som skal inn - spesielt for mobil. Tror det er tydeligere og mer intuitivt om de flyttes ned til høyre og venstre side av "boksen" - sentrert i høyden. I header kan det da være et ikon for listevisning, antall (N av NN) og knapp for å lukke.
![navigasjon - detalj](https://cloud.githubusercontent.com/assets/8926528/8365854/6081dd3a-1b90-11e5-8317-ea851bea31e1.png)

**Comment by atlefren** [comment]
fullscreen:
![image](https://cloud.githubusercontent.com/assets/1829927/8428826/1aba6142-1f22-11e5-9469-969a5e962db7.png)


mobil:
![image](https://cloud.githubusercontent.com/assets/1829927/8428843/40477b66-1f22-11e5-8366-b4844ebcec3b.png)
