### ISSUE TITLE
Visning av polygon for kulturminne-lokalitet

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#77]
Ved zoomnivå som viser en (eller få) lokasjoner - hent og vis polygon for de aktuelle lokasjonene. Samme farge som punkt på ramme og samme farge for fyll, men med gjennomsiktighet. Klikk på punkt og polygon går til samme detaljvisning. 

https://sparql.kulturminne.no/?default-graph-uri=&query=SELECT+%3Flok+where%0D%0A%7B+%0D%0A++%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Flokalitet%2F109073%3E+%3Chttps%3A%2F%2Fdata.kulturminne.no%2Faskeladden%2Fschema%2Fgeo%2Farea%2Fetrs89%3E+%3Flok+.%0D%0A%7D%0D%0A&format=application%2Fsparql-results%2Bjson&timeout=0&debug=on

**Comment by atlefren** [comment]
![image](https://cloud.githubusercontent.com/assets/1829927/8431629/00d0b042-1f3b-11e5-9427-c5e7d860b256.png)
