### ISSUE TITLE
Demonstrator: 2. verdenskrig

### ISSUE THREAD

**Issue by atlefren** [knreise/demonstratorer#87]
* Brukergenerert innhold - 
   * [x] Digitalt fortalt 
   * [x] Wikipedia
* [ ] Krigsminnelandskap Troms - fra Digitalt fortalt
* [ ] Innhold generert fra initiativer om krigens kulturminner -
* [x] Riksantikvaren 
* [x] Digitalt Museum 
* [ ] Klima- og miljødepartementet (KLD)
* [ ] Historiske foto
* [ ] Kulturminner
* [x] Innhold fra Jernbanemuseets initiativ knyttet til krigen og jernbanen

**Comment by atlefren** [comment]
@havardgj Har du noen inspill på hva som er "klart" av datasett her? Jeg tenker at  det burde finnes noen emneord i norvegiana eller noe slikt her?

Usikker på om det er fornuftig å bruke en generell wikipedia-spørring?

Kulturminner burde også kanskje filtreres på noe vis?

resten har vi vel ikke tilgang på enda?

**Comment by havardgj** [comment]
Det finnes nok dessverre ikke noe generelt kodeord for Norvegiana, så i første omgang tror jeg en kan trekke ut fra Digitalt Fortalt med de aktuelle og mest bruke kodeordene der: krig, andre-verdskrigen, krigsminne, andre-verdenskrig, krigen

Når det gjelder andre kilder så i Norvegiana så må jeg se litt på aktuelle spørringer - tror det vil være snakk om en kombinasjon av f.eks. tidfesting og mer generelle emneord - ser f.eks. at Digitalt Museum har 543 stedfestede poster datert 1940-45 med emneord "krig".

Wikipedia Norge har hatt et initiativ knyttet til 2. verdenskrig og krigens kulturminner - jeg skal sjekke om de aktuelle artiklene er tagget eller kategorisert på en måte som vi kan bruke.

Riksantikvaren skal også ha brukt et eget emneord for sitt prosjekt om krigens kulturminner, men også her må jeg sjekke hvordan dette er brukt og om vi kan spørre på dette i SPARQL-apiet.

Så inntil videre står vi vel igjen med Digitalt Fortalt.




6. aug. 2015 kl. 13.32 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


@havardgj<https://github.com/havardgj> Har du noen inspill på hva som er "klart" av datasett her? Jeg tenker at det burde finnes noen emneord i norvegiana eller noe slikt her?

Usikker på om det er fornuftig å bruke en generell wikipedia-spørring?

Kulturminner burde også kanskje filtreres på noe vis?

resten har vi vel ikke tilgang på enda?

**Comment by havardgj** [comment]
I tillegg er det jobbet med innhold hos Jernbanemuseet. Her har vi fått en generell API-beskrivelse, men det gjenstår å organisere selve innholdet i løsninen som brukes slik at vi enkelt kan hente alle de aktuelle stedfestede postene med ett kall.

6. aug. 2015 kl. 15.29 skrev Håvard Johansen <havard.johansen@kulturrad.no<mailto:havard.johansen@kulturrad.no>>:

Det finnes nok dessverre ikke noe generelt kodeord for Norvegiana, så i første omgang tror jeg en kan trekke ut fra Digitalt Fortalt med de aktuelle og mest bruke kodeordene der: krig, andre-verdskrigen, krigsminne, andre-verdenskrig, krigen

Når det gjelder andre kilder så i Norvegiana så må jeg se litt på aktuelle spørringer - tror det vil være snakk om en kombinasjon av f.eks. tidfesting og mer generelle emneord - ser f.eks. at Digitalt Museum har 543 stedfestede poster datert 1940-45 med emneord "krig".

Wikipedia Norge har hatt et initiativ knyttet til 2. verdenskrig og krigens kulturminner - jeg skal sjekke om de aktuelle artiklene er tagget eller kategorisert på en måte som vi kan bruke.

Riksantikvaren skal også ha brukt et eget emneord for sitt prosjekt om krigens kulturminner, men også her må jeg sjekke hvordan dette er brukt og om vi kan spørre på dette i SPARQL-apiet.

Så inntil videre står vi vel igjen med Digitalt Fortalt.




6. aug. 2015 kl. 13.32 skrev Atle Frenvik Sveen <notifications@github.com<mailto:notifications@github.com>>:


@havardgj<https://github.com/havardgj> Har du noen inspill på hva som er "klart" av datasett her? Jeg tenker at det burde finnes noen emneord i norvegiana eller noe slikt her?

Usikker på om det er fornuftig å bruke en generell wikipedia-spørring?

Kulturminner burde også kanskje filtreres på noe vis?

resten har vi vel ikke tilgang på enda?

**Comment by atlefren** [comment]
Har startet på denne nå.

det fungerer ikke med OR-queries på emneord mot norvegiana direkte, men via litt hacking og å sende flere requester fikk jeg til noe

Bruker DigitaltFortalt med disse emneordene: 
'krig', 
'andre-verdskrigen', 
'krigsminne', 
'andre-verdenskrig', 
'ww2', 
'krigsminneforteljingar', 
'krigen', 
'krigsminnelandskap-troms', 
'krigsminner', 
'ww2-nord', 
'ww2-troms', 
'krigshistorie', 
'krigsminneprosjekt-sør-troms', 
'verdenskrig', 
'2.-verdenskrig', 
'2.-verdenskrigen'

**Comment by atlefren** [comment]
- Jeg tror ellers det hadde vært fint med et uttrekk fra Digitalt Museum. Klarer du enkelt å «oversette» denne spørringen direkte til Digitalt Museum til en spørring mot Norvegiana:  https://digitaltmuseum.no/search?query=krig&from_year=1940&to_year=1945&coordinate=1&advanced_search=1

- Jernbanemuseet må som sagt organisere sitt innhold slik at vi kan få alt relevant innhold med en spørring av samme type som du bruker nå.
