### ISSUE TITLE
Mulighet for bruk av emneord fra Norvegiana

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#96]
Legge til mulighet for bruk av emneord for spørringer mot Norvegiana i generator - i første omgang ett emneord og for Digitalt Fortalt.

Digitalt Fortalt - ett emneord:
http://kulturnett2.delving.org/api/search?query=dc_subject_text:dovre-piloten&delving_spec%3Adifo&rows=1000&format=json

**Comment by atlefren** [comment]
Jeg ser at man også kan skrive spørringen over som http://kulturnett2.delving.org/api/search?query=delving_spec%3Adifo&rows=1000&format=json&qf=dc_subject_text:dovre-piloten 

er det noen forskjell på dette? Har allerede støtte i stor grad for metoden med qf=

**Comment by havardgj** [comment]
I praksis ser jeg ikke den store forskjellen, men i prinsippet ser det ut til at query er "the search term you want to search on", mens qf er en form for fasettert filtrering. Men er det enklere å fortsette med qf nå så gjør det.

**Comment by atlefren** [comment]
![image](https://cloud.githubusercontent.com/assets/1829927/9061870/f77dc56c-3abe-11e5-8dca-c52554634da5.png)

@havardgj fint om du tester dette på http://knreise.github.io/demonstratorer/demonstratorer/generator.html så lukker jeg denne og merger til master hvis ok

**Comment by havardgj** [comment]
Ser ut til å fungere fint det.

________________________________

**Comment by atlefren** [comment]
Kan være det kan stiles bedre, men hvis du er fornøyd med slik det ser ut nå så tror jeg det blir sånn?

**Comment by atlefren** [comment]
Merget til master, lukker
