### ISSUE TITLE
Undersøke bruk av samme kartmarkør for 3D-kart som i 2D-kart 

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#97]
Samme PNG hvis mulig - hvis ikke se om det kan lages en fil som er så lik som mulig

**Comment by atlefren** [comment]
Måtte splitte png'en som l.awesome-markers bruker, da cesium ikke støtter sprites.

![image](https://cloud.githubusercontent.com/assets/1829927/9085491/84bf0e86-3b7d-11e5-99b3-b21c0a199563.png)


Demo:
http://knreise.github.io/demonstratorer/demonstratorer/config_3d.html?datasets=difo%2Cark_hist%2Cwikipedia&line=utno%2F2.8158&layer=nib

**Comment by havardgj** [comment]
Ser veldig bra ut! Absolutt likt nok til at en ser at de er i samme "familie" som de som brukes i 2D-kartene.


Mye vil ha mer... Er det enkelt å sette selve linje til en farge - og ikke to som nå? Fant disse eksemplene:

http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Polyline.html&label=Showcases

Synes den varianten som her heter "Orange line with black outline at height and following the surface" fungerer best, men kanskje "on the surface" i stedet...?



Håvard


________________________________

**Comment by atlefren** [comment]
Fargendring skal være greit ja.

Du vil ha den orange med svart outline?

**Comment by atlefren** [comment]
lukker denne
