### ISSUE TITLE
Versjon av Gudbrandsdalsleden med bruk av linjekart

### ISSUE THREAD

**Issue by havardgj** [knreise/demonstratorer#98]
Med modul for navigasjon i tillegg til pilnavigasjon - minikart med hele leden/området og flyttbar utsnittsmarkør

**Comment by atlefren** [comment]
Da er denne på plass, kan være det mangler noen datasett, har lagt inn følgende:
- difo
- Artsdatabanken
- wikipedia
- Trondheim byarkiv

(tror naturvernområder som flater blir mer jobb)

Demo på http://knreise.github.io/demonstratorer/experiments/linemap.html

fint om du verifiserer @havardgj

**Comment by havardgj** [comment]
Ser bra ut med modul med minikart for navigasjon. Og den ser ut til å fungere for navigasjon, men det ser ut til at pilnavigasjonen ikke fungerer så bra - etter at en har brukt kartmodulen. Bruker en pilene da så hopper kartet litt utforutsigbart og følger ikke linja slik den gjør før. Testet i Chrome.


________________________________

**Comment by atlefren** [comment]
Ja, var en bug relatert til keyboard-bruk der. 

Skal være rettet nå, fint om du kan re-teste

**Comment by havardgj** [comment]
Navigasjonen fungerer fint nå.

Jeg ser ellers at alle punkter nå fjernes og lastes på nytt når man beveger seg ett steg med pilene. Lurer på om det hadde vært bedre om de ble stående til nye punkter var lastet inn hvis det er mulig. Tror det hadde gjort opplevelsen litt bedre - færre ting som endrer seg kan kanskje være bra når navigasjon og visning ellers er litt utradisjonell.

________________________________

**Comment by atlefren** [comment]
jepp, enig i det. 

Tror jeg hadde en eller annen form for begrunnelse, men ser nå at det er best å oppdatere når man har nye

**Comment by atlefren** [comment]
Tre ønsker om justeringer:
- Ta ut Artsdatabanken og lagt til den generelle Arkeologi og histori som datasett? 
- Legge til Digitalt fortalt i bunnlinja - i tillegg til Wikipedia?
- Se om det er mulig å bruke en større variant av bildene som brukes i bunnlinja - oppløsningen er nå alt for liten i forhold til den størrelsen som vises.

**Comment by atlefren** [comment]
Digitalt fortalt er med

**Comment by atlefren** [comment]
Har gjort de siste endringene:
1. Listen med datasett er nå som følger: Kulturminner, DiFo, Musit, DiMu, Wikipedia, trondheim byarkiv
2. Digitalt fortalt lå allerede inne
3. Bruker nå "fullstørrelse"-bildene i stripa under, dette fører til at man laster en del mer data, men bildene ser bra ut

Siden det ble VELDIG mye data har jeg begrenset kartet til å vise de 200 nærmeste punktene til punktet man "står på" i kartet. Synes dette fungerer greit.

Demo på http://knreise.github.io/demonstratorer/experiments/linemap.html

**Comment by atlefren** [comment]
@havardgj ser på alternative kilder for linjegeometrien

**Comment by atlefren** [comment]
Lukker denne etter fikser
